package org.openfinance.repository;

import static org.assertj.core.api.Assertions.*;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openfinance.entity.Account;
import org.openfinance.entity.AccountType;
import org.openfinance.entity.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

/**
 * Integration tests for AccountRepository.
 *
 * <p>
 * Uses @DataJpaTest which configures an in-memory H2 database and provides
 * transactional test
 * execution with rollback.
 *
 * <p>
 * Flyway is disabled for these tests - schema is auto-generated by Hibernate.
 *
 * <p>
 * Requirement REQ-2.2: Account repository tests covering CRUD and custom
 * queries
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(properties = {
                "spring.flyway.enabled=false",
                "spring.jpa.hibernate.ddl-auto=create-drop",
                "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
})
@DisplayName("AccountRepository Integration Tests")
class AccountRepositoryTest {

        @Autowired
        private AccountRepository accountRepository;

        @Autowired
        private UserRepository userRepository;

        private User testUser;
        private Account testAccount;

        @BeforeEach
        void setUp() {
                // Clear repositories before each test
                accountRepository.deleteAll();
                userRepository.deleteAll();

                // Create and save a test user
                testUser = User.builder()
                                .username("testuser")
                                .email("test@example.com")
                                .passwordHash("$2a$10$hashedPasswordExample123456789")
                                .masterPasswordSalt("base64EncodedSaltExample==")
                                .build();
                testUser = userRepository.save(testUser);

                // Create a test account
                testAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Test Checking Account")
                                .type(AccountType.CHECKING)
                                .currency("USD")
                                .balance(new BigDecimal("1000.00"))
                                .description("Primary checking account")
                                .isActive(true)
                                .build();
        }

        // === CRUD Operation Tests ===

        @Test
        @DisplayName("Should save account and generate ID")
        void shouldSaveAccountAndGenerateId() {
                // When
                Account savedAccount = accountRepository.save(testAccount);

                // Then
                assertThat(savedAccount).isNotNull();
                assertThat(savedAccount.getId()).isNotNull();
                assertThat(savedAccount.getUserId()).isEqualTo(testUser.getId());
                assertThat(savedAccount.getName()).isEqualTo("Test Checking Account");
                assertThat(savedAccount.getType()).isEqualTo(AccountType.CHECKING);
                assertThat(savedAccount.getCurrency()).isEqualTo("USD");
                assertThat(savedAccount.getBalance()).isEqualByComparingTo(new BigDecimal("1000.00"));
                assertThat(savedAccount.getIsActive()).isTrue();
                assertThat(savedAccount.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should find account by ID")
        void shouldFindAccountById() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);

                // When
                Optional<Account> found = accountRepository.findById(savedAccount.getId());

                // Then
                assertThat(found).isPresent();
                assertThat(found.get().getName()).isEqualTo("Test Checking Account");
        }

        @Test
        @DisplayName("Should update account balance")
        void shouldUpdateAccountBalance() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);
                BigDecimal newBalance = new BigDecimal("1500.00");

                // When
                savedAccount.setBalance(newBalance);
                Account updatedAccount = accountRepository.save(savedAccount);

                // Then
                assertThat(updatedAccount.getBalance()).isEqualByComparingTo(newBalance);
                assertThat(updatedAccount.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should soft delete account by setting isActive to false")
        void shouldSoftDeleteAccount() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);

                // When
                savedAccount.setIsActive(false);
                Account deletedAccount = accountRepository.save(savedAccount);

                // Then
                assertThat(deletedAccount.getIsActive()).isFalse();
                assertThat(accountRepository.findById(deletedAccount.getId())).isPresent();
        }

        @Test
        @DisplayName("Should hard delete account")
        void shouldHardDeleteAccount() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);
                Long accountId = savedAccount.getId();

                // When
                accountRepository.delete(savedAccount);

                // Then
                assertThat(accountRepository.findById(accountId)).isEmpty();
        }

        // === Custom Query Tests ===

        @Test
        @DisplayName("Should find accounts by user ID")
        void shouldFindAccountsByUserId() {
                // Given
                accountRepository.save(testAccount);
                Account secondAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Savings Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(new BigDecimal("5000.00"))
                                .isActive(true)
                                .build();
                accountRepository.save(secondAccount);

                // When
                List<Account> accounts = accountRepository.findByUserId(testUser.getId());

                // Then
                assertThat(accounts).hasSize(2);
                assertThat(accounts)
                                .extracting(Account::getName)
                                .containsExactlyInAnyOrder("Test Checking Account", "Savings Account");
        }

        @Test
        @DisplayName("Should find only active accounts by user ID")
        void shouldFindActiveAccountsByUserId() {
                // Given
                accountRepository.save(testAccount);
                Account inactiveAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Closed Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(BigDecimal.ZERO)
                                .isActive(false)
                                .build();
                accountRepository.save(inactiveAccount);

                // When
                List<Account> activeAccounts = accountRepository.findByUserIdAndIsActive(testUser.getId(), true);

                // Then
                assertThat(activeAccounts).hasSize(1);
                assertThat(activeAccounts.get(0).getName()).isEqualTo("Test Checking Account");
                assertThat(activeAccounts.get(0).getIsActive()).isTrue();
        }

        @Test
        @DisplayName("Should find accounts by user ID and type")
        void shouldFindAccountsByUserIdAndType() {
                // Given
                accountRepository.save(testAccount); // CHECKING
                Account savingsAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Savings Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(new BigDecimal("5000.00"))
                                .isActive(true)
                                .build();
                accountRepository.save(savingsAccount);

                // When
                List<Account> checkingAccounts = accountRepository.findByUserIdAndType(testUser.getId(),
                                AccountType.CHECKING);

                // Then
                assertThat(checkingAccounts).hasSize(1);
                assertThat(checkingAccounts.get(0).getType()).isEqualTo(AccountType.CHECKING);
        }

        @Test
        @DisplayName("Should find account by ID and user ID")
        void shouldFindAccountByIdAndUserId() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);

                // When
                Optional<Account> found = accountRepository.findByIdAndUserId(savedAccount.getId(), testUser.getId());

                // Then
                assertThat(found).isPresent();
                assertThat(found.get().getName()).isEqualTo("Test Checking Account");
        }

        @Test
        @DisplayName("Should not find account with wrong user ID")
        void shouldNotFindAccountWithWrongUserId() {
                // Given
                Account savedAccount = accountRepository.save(testAccount);
                Long wrongUserId = 999L;

                // When
                Optional<Account> found = accountRepository.findByIdAndUserId(savedAccount.getId(), wrongUserId);

                // Then
                assertThat(found).isEmpty();
        }

        @Test
        @DisplayName("Should check if account exists by user ID and name")
        void shouldCheckIfAccountExistsByUserIdAndName() {
                // Given
                accountRepository.save(testAccount);

                // When
                boolean exists = accountRepository.existsByUserIdAndName(testUser.getId(), "Test Checking Account");
                boolean notExists = accountRepository.existsByUserIdAndName(testUser.getId(), "Non-existent Account");

                // Then
                assertThat(exists).isTrue();
                assertThat(notExists).isFalse();
        }

        @Test
        @DisplayName("Should count accounts by user ID")
        void shouldCountAccountsByUserId() {
                // Given
                accountRepository.save(testAccount);
                Account secondAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Savings Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(new BigDecimal("5000.00"))
                                .isActive(true)
                                .build();
                accountRepository.save(secondAccount);

                // When
                long count = accountRepository.countByUserId(testUser.getId());

                // Then
                assertThat(count).isEqualTo(2);
        }

        @Test
        @DisplayName("Should count active accounts by user ID")
        void shouldCountActiveAccountsByUserId() {
                // Given
                accountRepository.save(testAccount);
                Account inactiveAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Closed Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(BigDecimal.ZERO)
                                .isActive(false)
                                .build();
                accountRepository.save(inactiveAccount);

                // When
                long activeCount = accountRepository.countByUserIdAndIsActive(testUser.getId(), true);

                // Then
                assertThat(activeCount).isEqualTo(1);
        }

        // === Multi-Account Type Tests ===

        @Test
        @DisplayName("Should handle multiple account types for same user")
        void shouldHandleMultipleAccountTypesForSameUser() {
                // Given
                Account checking = testAccount; // CHECKING
                Account savings = Account.builder()
                                .userId(testUser.getId())
                                .name("Savings Account")
                                .type(AccountType.SAVINGS)
                                .currency("USD")
                                .balance(new BigDecimal("5000.00"))
                                .isActive(true)
                                .build();
                Account creditCard = Account.builder()
                                .userId(testUser.getId())
                                .name("Credit Card")
                                .type(AccountType.CREDIT_CARD)
                                .currency("USD")
                                .balance(new BigDecimal("500.00"))
                                .isActive(true)
                                .build();

                accountRepository.save(checking);
                accountRepository.save(savings);
                accountRepository.save(creditCard);

                // When
                List<Account> allAccounts = accountRepository.findByUserId(testUser.getId());

                // Then
                assertThat(allAccounts).hasSize(3);
                assertThat(allAccounts)
                                .extracting(Account::getType)
                                .containsExactlyInAnyOrder(
                                                AccountType.CHECKING, AccountType.SAVINGS, AccountType.CREDIT_CARD);
        }

        // === Empty Result Tests ===

        @Test
        @DisplayName("Should return empty list when user has no accounts")
        void shouldReturnEmptyListWhenUserHasNoAccounts() {
                // Given - no accounts saved

                // When
                List<Account> accounts = accountRepository.findByUserId(testUser.getId());

                // Then
                assertThat(accounts).isEmpty();
        }

        @Test
        @DisplayName("Should return empty list when filtering by non-existent type")
        void shouldReturnEmptyListWhenFilteringByNonExistentType() {
                // Given
                accountRepository.save(testAccount); // CHECKING type

                // When
                List<Account> investmentAccounts = accountRepository.findByUserIdAndType(testUser.getId(),
                                AccountType.INVESTMENT);

                // Then
                assertThat(investmentAccounts).isEmpty();
        }
}
