package org.openfinance.repository;

import static org.assertj.core.api.Assertions.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openfinance.entity.Account;
import org.openfinance.entity.AccountType;
import org.openfinance.entity.Asset;
import org.openfinance.entity.AssetCondition;
import org.openfinance.entity.AssetType;
import org.openfinance.entity.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

/**
 * Integration tests for AssetRepository.
 *
 * <p>
 * Uses @DataJpaTest which configures an in-memory H2 database and provides
 * transactional test
 * execution with rollback.
 *
 * <p>
 * Flyway is disabled for these tests - schema is auto-generated by Hibernate.
 *
 * <p>
 * Requirement REQ-2.6: Asset repository tests covering CRUD and custom queries
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(properties = {
                "spring.flyway.enabled=false",
                "spring.jpa.hibernate.ddl-auto=create-drop",
                "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
})
@DisplayName("AssetRepository Integration Tests")
class AssetRepositoryTest {

        @Autowired
        private AssetRepository assetRepository;

        @Autowired
        private UserRepository userRepository;

        @Autowired
        private AccountRepository accountRepository;

        private User testUser;
        private User otherUser;
        private Account testAccount;
        private Asset testAsset;

        @BeforeEach
        void setUp() {
                // Clear repositories before each test
                assetRepository.deleteAll();
                accountRepository.deleteAll();
                userRepository.deleteAll();

                // Create and save test users
                testUser = User.builder()
                                .username("assetuser")
                                .email("asset@example.com")
                                .passwordHash("$2a$10$hashedPasswordExample123456789")
                                .masterPasswordSalt("base64EncodedSaltExample==")
                                .build();
                testUser = userRepository.save(testUser);

                otherUser = User.builder()
                                .username("otheruser")
                                .email("other@example.com")
                                .passwordHash("$2a$10$hashedPasswordExample123456789")
                                .masterPasswordSalt("base64EncodedSaltExample==")
                                .build();
                otherUser = userRepository.save(otherUser);

                // Create and save a test account
                testAccount = Account.builder()
                                .userId(testUser.getId())
                                .name("Brokerage Account")
                                .type(AccountType.INVESTMENT)
                                .currency("USD")
                                .balance(new BigDecimal("10000.00"))
                                .isActive(true)
                                .build();
                testAccount = accountRepository.save(testAccount);

                // Create a test asset
                testAsset = Asset.builder()
                                .userId(testUser.getId())
                                .accountId(testAccount.getId())
                                .name("Apple Inc.")
                                .type(AssetType.STOCK)
                                .symbol("AAPL")
                                .quantity(new BigDecimal("100.00"))
                                .purchasePrice(new BigDecimal("150.00"))
                                .currentPrice(new BigDecimal("175.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2024, 1, 15))
                                .notes("Tech stock investment")
                                .lastUpdated(LocalDateTime.now())
                                .build();
        }

        // === CRUD Operation Tests ===

        @Test
        @DisplayName("Should save asset and generate ID")
        void shouldSaveAssetAndGenerateId() {
                // When
                Asset savedAsset = assetRepository.save(testAsset);

                // Then
                assertThat(savedAsset).isNotNull();
                assertThat(savedAsset.getId()).isNotNull();
                assertThat(savedAsset.getUserId()).isEqualTo(testUser.getId());
                assertThat(savedAsset.getAccountId()).isEqualTo(testAccount.getId());
                assertThat(savedAsset.getName()).isEqualTo("Apple Inc.");
                assertThat(savedAsset.getType()).isEqualTo(AssetType.STOCK);
                assertThat(savedAsset.getSymbol()).isEqualTo("AAPL");
                assertThat(savedAsset.getQuantity()).isEqualByComparingTo(new BigDecimal("100.00"));
                assertThat(savedAsset.getPurchasePrice()).isEqualByComparingTo(new BigDecimal("150.00"));
                assertThat(savedAsset.getCurrentPrice()).isEqualByComparingTo(new BigDecimal("175.00"));
                assertThat(savedAsset.getCurrency()).isEqualTo("USD");
                assertThat(savedAsset.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should find asset by ID")
        void shouldFindAssetById() {
                // Given
                Asset savedAsset = assetRepository.save(testAsset);

                // When
                Optional<Asset> foundAsset = assetRepository.findById(savedAsset.getId());

                // Then
                assertThat(foundAsset).isPresent();
                assertThat(foundAsset.get().getId()).isEqualTo(savedAsset.getId());
                assertThat(foundAsset.get().getName()).isEqualTo("Apple Inc.");
        }

        @Test
        @DisplayName("Should update existing asset")
        void shouldUpdateExistingAsset() {
                // Given
                Asset savedAsset = assetRepository.save(testAsset);

                // When
                savedAsset.setCurrentPrice(new BigDecimal("180.00"));
                savedAsset.setQuantity(new BigDecimal("150.00"));
                savedAsset.setLastUpdated(LocalDateTime.now());
                Asset updatedAsset = assetRepository.save(savedAsset);

                // Then
                assertThat(updatedAsset.getId()).isEqualTo(savedAsset.getId());
                assertThat(updatedAsset.getCurrentPrice()).isEqualByComparingTo(new BigDecimal("180.00"));
                assertThat(updatedAsset.getQuantity()).isEqualByComparingTo(new BigDecimal("150.00"));
                assertThat(updatedAsset.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should delete asset by ID")
        void shouldDeleteAssetById() {
                // Given
                Asset savedAsset = assetRepository.save(testAsset);

                // When
                assetRepository.deleteById(savedAsset.getId());

                // Then
                Optional<Asset> deletedAsset = assetRepository.findById(savedAsset.getId());
                assertThat(deletedAsset).isEmpty();
        }

        // === Custom Query Tests ===

        @Test
        @DisplayName("Should find all assets by user ID")
        void shouldFindAllAssetsByUserId() {
                // Given
                Asset asset1 = assetRepository.save(testAsset);
                Asset asset2 = Asset.builder()
                                .userId(testUser.getId())
                                .name("Microsoft Corp")
                                .type(AssetType.STOCK)
                                .symbol("MSFT")
                                .quantity(new BigDecimal("50.00"))
                                .purchasePrice(new BigDecimal("300.00"))
                                .currentPrice(new BigDecimal("350.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2024, 2, 1))
                                .build();
                asset2 = assetRepository.save(asset2);

                // When
                List<Asset> userAssets = assetRepository.findByUserId(testUser.getId());

                // Then
                assertThat(userAssets).hasSize(2);
                assertThat(userAssets)
                                .extracting(Asset::getId)
                                .containsExactlyInAnyOrder(asset1.getId(), asset2.getId());
        }

        @Test
        @DisplayName("Should find assets by account ID")
        void shouldFindAssetsByAccountId() {
                // Given
                assetRepository.save(testAsset);

                Asset assetWithoutAccount = Asset.builder()
                                .userId(testUser.getId())
                                .accountId(null) // No account
                                .name("Bitcoin")
                                .type(AssetType.CRYPTO)
                                .symbol("BTC-USD")
                                .quantity(new BigDecimal("0.5"))
                                .purchasePrice(new BigDecimal("40000.00"))
                                .currentPrice(new BigDecimal("45000.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2024, 3, 1))
                                .build();
                assetRepository.save(assetWithoutAccount);

                // When
                List<Asset> accountAssets = assetRepository.findByAccountId(testAccount.getId());

                // Then
                assertThat(accountAssets).hasSize(1);
                assertThat(accountAssets.get(0).getName()).isEqualTo("Apple Inc.");
        }

        @Test
        @DisplayName("Should find assets by user ID and type")
        void shouldFindAssetsByUserIdAndType() {
                // Given
                assetRepository.save(testAsset); // STOCK type

                Asset cryptoAsset = Asset.builder()
                                .userId(testUser.getId())
                                .name("Ethereum")
                                .type(AssetType.CRYPTO)
                                .quantity(new BigDecimal("10.00"))
                                .purchasePrice(new BigDecimal("2000.00"))
                                .currentPrice(new BigDecimal("2500.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();
                assetRepository.save(cryptoAsset);

                // When
                List<Asset> stockAssets = assetRepository.findByUserIdAndType(testUser.getId(), AssetType.STOCK);
                List<Asset> cryptoAssets = assetRepository.findByUserIdAndType(testUser.getId(), AssetType.CRYPTO);

                // Then
                assertThat(stockAssets).hasSize(1);
                assertThat(stockAssets.get(0).getName()).isEqualTo("Apple Inc.");
                assertThat(cryptoAssets).hasSize(1);
                assertThat(cryptoAssets.get(0).getName()).isEqualTo("Ethereum");
        }

        @Test
        @DisplayName("Should find assets by user ID and symbol")
        void shouldFindAssetsByUserIdAndSymbol() {
                // Given
                assetRepository.save(testAsset);

                // Add another AAPL asset in different account
                Asset anotherApple = Asset.builder()
                                .userId(testUser.getId())
                                .accountId(null)
                                .name("Apple Inc.")
                                .type(AssetType.STOCK)
                                .symbol("AAPL")
                                .quantity(new BigDecimal("50.00"))
                                .purchasePrice(new BigDecimal("160.00"))
                                .currentPrice(new BigDecimal("175.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();
                assetRepository.save(anotherApple);

                // When
                List<Asset> appleAssets = assetRepository.findByUserIdAndSymbol(testUser.getId(), "AAPL");

                // Then
                assertThat(appleAssets).hasSize(2);
                assertThat(appleAssets).allMatch(asset -> asset.getSymbol().equals("AAPL"));
        }

        @Test
        @DisplayName("Should find asset by ID and user ID (authorization check)")
        void shouldFindAssetByIdAndUserId() {
                // Given
                Asset savedAsset = assetRepository.save(testAsset);

                // When - correct user
                Optional<Asset> foundAsset = assetRepository.findByIdAndUserId(savedAsset.getId(), testUser.getId());

                // Then
                assertThat(foundAsset).isPresent();
                assertThat(foundAsset.get().getId()).isEqualTo(savedAsset.getId());

                // When - wrong user
                Optional<Asset> notFoundAsset = assetRepository.findByIdAndUserId(savedAsset.getId(),
                                otherUser.getId());

                // Then
                assertThat(notFoundAsset).isEmpty();
        }

        @Test
        @DisplayName("Should find assets by user ID and account ID")
        void shouldFindAssetsByUserIdAndAccountId() {
                // Given
                assetRepository.save(testAsset);

                // When
                List<Asset> accountAssets = assetRepository.findByUserIdAndAccountId(testUser.getId(),
                                testAccount.getId());

                // Then
                assertThat(accountAssets).hasSize(1);
                assertThat(accountAssets.get(0).getAccountId()).isEqualTo(testAccount.getId());
        }

        @Test
        @DisplayName("Should count assets by user ID")
        void shouldCountAssetsByUserId() {
                // Given
                assetRepository.save(testAsset);
                assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("Tesla Inc")
                                                .type(AssetType.STOCK)
                                                .quantity(new BigDecimal("20.00"))
                                                .purchasePrice(new BigDecimal("200.00"))
                                                .currentPrice(new BigDecimal("250.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.now())
                                                .build());

                // When
                long count = assetRepository.countByUserId(testUser.getId());

                // Then
                assertThat(count).isEqualTo(2);
        }

        @Test
        @DisplayName("Should count assets by user ID and type")
        void shouldCountAssetsByUserIdAndType() {
                // Given
                assetRepository.save(testAsset); // STOCK
                assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("Vanguard Total Stock Market ETF")
                                                .type(AssetType.ETF)
                                                .quantity(new BigDecimal("100.00"))
                                                .purchasePrice(new BigDecimal("200.00"))
                                                .currentPrice(new BigDecimal("220.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.now())
                                                .build());

                // When
                long stockCount = assetRepository.countByUserIdAndType(testUser.getId(), AssetType.STOCK);
                long etfCount = assetRepository.countByUserIdAndType(testUser.getId(), AssetType.ETF);

                // Then
                assertThat(stockCount).isEqualTo(1);
                assertThat(etfCount).isEqualTo(1);
        }

        @Test
        @DisplayName("Should find assets with symbols")
        void shouldFindAssetsWithSymbols() {
                // Given
                assetRepository.save(testAsset); // Has symbol "AAPL"

                Asset realEstate = Asset.builder()
                                .userId(testUser.getId())
                                .name("Rental Property")
                                .type(AssetType.REAL_ESTATE)
                                .symbol(null) // No symbol
                                .quantity(new BigDecimal("1.00"))
                                .purchasePrice(new BigDecimal("300000.00"))
                                .currentPrice(new BigDecimal("350000.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();
                assetRepository.save(realEstate);

                // When
                List<Asset> assetsWithSymbols = assetRepository.findAssetsWithSymbols(testUser.getId());

                // Then
                assertThat(assetsWithSymbols).hasSize(1);
                assertThat(assetsWithSymbols.get(0).getSymbol()).isEqualTo("AAPL");
        }

        // === Edge Case Tests ===

        @Test
        @DisplayName("Should return empty list when no assets exist for user")
        void shouldReturnEmptyListWhenNoAssetsExist() {
                // When
                List<Asset> assets = assetRepository.findByUserId(testUser.getId());

                // Then
                assertThat(assets).isEmpty();
        }

        @Test
        @DisplayName("Should handle assets without account ID")
        void shouldHandleAssetsWithoutAccountId() {
                // Given
                Asset assetWithoutAccount = Asset.builder()
                                .userId(testUser.getId())
                                .accountId(null)
                                .name("Gold Bars")
                                .type(AssetType.COMMODITY)
                                .quantity(new BigDecimal("10.00"))
                                .purchasePrice(new BigDecimal("1800.00"))
                                .currentPrice(new BigDecimal("2000.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();

                // When
                Asset savedAsset = assetRepository.save(assetWithoutAccount);

                // Then
                assertThat(savedAsset.getAccountId()).isNull();
                List<Asset> userAssets = assetRepository.findByUserId(testUser.getId());
                assertThat(userAssets).hasSize(1);
        }

        @Test
        @DisplayName("Should handle fractional quantities (crypto)")
        void shouldHandleFractionalQuantities() {
                // Given
                Asset cryptoAsset = Asset.builder()
                                .userId(testUser.getId())
                                .name("Bitcoin")
                                .type(AssetType.CRYPTO)
                                .quantity(new BigDecimal("0.12345678")) // 8 decimal places
                                .purchasePrice(new BigDecimal("40000.00"))
                                .currentPrice(new BigDecimal("45000.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();

                // When
                Asset savedAsset = assetRepository.save(cryptoAsset);

                // Then
                assertThat(savedAsset.getQuantity()).isEqualByComparingTo(new BigDecimal("0.12345678"));
        }

        @Test
        @DisplayName("Should enforce user isolation")
        void shouldEnforceUserIsolation() {
                // Given
                Asset user1Asset = assetRepository.save(testAsset);

                Asset user2Asset = Asset.builder()
                                .userId(otherUser.getId())
                                .name("Google LLC")
                                .type(AssetType.STOCK)
                                .quantity(new BigDecimal("100.00"))
                                .purchasePrice(new BigDecimal("100.00"))
                                .currentPrice(new BigDecimal("120.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();
                user2Asset = assetRepository.save(user2Asset);

                // When
                List<Asset> user1Assets = assetRepository.findByUserId(testUser.getId());
                List<Asset> user2Assets = assetRepository.findByUserId(otherUser.getId());

                // Then
                assertThat(user1Assets).hasSize(1);
                assertThat(user1Assets.get(0).getId()).isEqualTo(user1Asset.getId());
                assertThat(user2Assets).hasSize(1);
                assertThat(user2Assets.get(0).getId()).isEqualTo(user2Asset.getId());
        }

        // === Physical Asset Tests ===

        @Test
        @DisplayName("Should save and retrieve physical asset with all fields")
        void shouldSavePhysicalAssetWithAllFields() {
                // Given
                Asset physicalAsset = Asset.builder()
                                .userId(testUser.getId())
                                .accountId(null)
                                .name("Tesla Model 3")
                                .type(AssetType.VEHICLE)
                                .serialNumber("5YJ3E1EB9KF123456")
                                .brand("Tesla")
                                .model("Model 3 Long Range")
                                .condition(AssetCondition.EXCELLENT)
                                .warrantyExpiration(LocalDate.of(2028, 6, 1))
                                .usefulLifeYears(15)
                                .photoPath("/photos/tesla-model3.jpg")
                                .quantity(new BigDecimal("1.0"))
                                .purchasePrice(new BigDecimal("50000.00"))
                                .currentPrice(new BigDecimal("45000.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2023, 6, 1))
                                .notes("Personal vehicle")
                                .build();

                // When
                Asset savedAsset = assetRepository.save(physicalAsset);
                Asset retrieved = assetRepository.findById(savedAsset.getId()).orElseThrow();

                // Then
                assertThat(retrieved.getId()).isEqualTo(savedAsset.getId());
                assertThat(retrieved.getName()).isEqualTo("Tesla Model 3");
                assertThat(retrieved.getType()).isEqualTo(AssetType.VEHICLE);
                assertThat(retrieved.getSerialNumber()).isEqualTo("5YJ3E1EB9KF123456");
                assertThat(retrieved.getBrand()).isEqualTo("Tesla");
                assertThat(retrieved.getModel()).isEqualTo("Model 3 Long Range");
                assertThat(retrieved.getCondition()).isEqualTo(AssetCondition.EXCELLENT);
                assertThat(retrieved.getWarrantyExpiration()).isEqualTo(LocalDate.of(2028, 6, 1));
                assertThat(retrieved.getUsefulLifeYears()).isEqualTo(15);
                assertThat(retrieved.getPhotoPath()).isEqualTo("/photos/tesla-model3.jpg");
        }

        @Test
        @DisplayName("Should find physical assets by user ID and type")
        void shouldFindPhysicalAssetsByType() {
                // Given - save physical assets of different types
                assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("Tesla Model 3")
                                                .type(AssetType.VEHICLE)
                                                .quantity(new BigDecimal("1.0"))
                                                .purchasePrice(new BigDecimal("50000.00"))
                                                .currentPrice(new BigDecimal("45000.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.now())
                                                .build());

                assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("MacBook Pro")
                                                .type(AssetType.ELECTRONICS)
                                                .quantity(new BigDecimal("1.0"))
                                                .purchasePrice(new BigDecimal("2500.00"))
                                                .currentPrice(new BigDecimal("2000.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.now())
                                                .build());

                assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("Rolex Submariner")
                                                .type(AssetType.JEWELRY)
                                                .quantity(new BigDecimal("1.0"))
                                                .purchasePrice(new BigDecimal("10000.00"))
                                                .currentPrice(new BigDecimal("15000.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.now())
                                                .build());

                // When
                List<Asset> vehicles = assetRepository.findByUserIdAndType(testUser.getId(), AssetType.VEHICLE);
                List<Asset> electronics = assetRepository.findByUserIdAndType(testUser.getId(), AssetType.ELECTRONICS);
                List<Asset> jewelry = assetRepository.findByUserIdAndType(testUser.getId(), AssetType.JEWELRY);

                // Then
                assertThat(vehicles).hasSize(1);
                assertThat(vehicles.get(0).getName()).isEqualTo("Tesla Model 3");
                assertThat(electronics).hasSize(1);
                assertThat(electronics.get(0).getName()).isEqualTo("MacBook Pro");
                assertThat(jewelry).hasSize(1);
                assertThat(jewelry.get(0).getName()).isEqualTo("Rolex Submariner");
        }

        @Test
        @DisplayName("Should handle physical assets without optional fields")
        void shouldHandlePhysicalAssetsWithoutOptionalFields() {
                // Given - physical asset with minimal fields
                Asset minimalAsset = Asset.builder()
                                .userId(testUser.getId())
                                .name("Vintage Furniture")
                                .type(AssetType.FURNITURE)
                                .serialNumber(null) // Optional
                                .brand(null) // Optional
                                .model(null) // Optional
                                .condition(null) // Optional
                                .warrantyExpiration(null) // Optional
                                .usefulLifeYears(null) // Optional
                                .photoPath(null) // Optional
                                .quantity(new BigDecimal("1.0"))
                                .purchasePrice(new BigDecimal("500.00"))
                                .currentPrice(new BigDecimal("600.00"))
                                .currency("USD")
                                .purchaseDate(LocalDate.now())
                                .build();

                // When
                Asset savedAsset = assetRepository.save(minimalAsset);
                Asset retrieved = assetRepository.findById(savedAsset.getId()).orElseThrow();

                // Then
                assertThat(retrieved.getSerialNumber()).isNull();
                assertThat(retrieved.getBrand()).isNull();
                assertThat(retrieved.getModel()).isNull();
                assertThat(retrieved.getCondition()).isNull();
                assertThat(retrieved.getWarrantyExpiration()).isNull();
                assertThat(retrieved.getUsefulLifeYears()).isNull();
                assertThat(retrieved.getPhotoPath()).isNull();
        }

        @Test
        @DisplayName("Should save all physical asset types correctly")
        void shouldSaveAllPhysicalAssetTypes() {
                // Given
                AssetType[] physicalTypes = {
                                AssetType.VEHICLE,
                                AssetType.JEWELRY,
                                AssetType.COLLECTIBLE,
                                AssetType.ELECTRONICS,
                                AssetType.FURNITURE
                };

                // When - save one of each type
                for (AssetType type : physicalTypes) {
                        assetRepository.save(
                                        Asset.builder()
                                                        .userId(testUser.getId())
                                                        .name("Test " + type.name())
                                                        .type(type)
                                                        .quantity(new BigDecimal("1.0"))
                                                        .purchasePrice(new BigDecimal("1000.00"))
                                                        .currentPrice(new BigDecimal("900.00"))
                                                        .currency("USD")
                                                        .purchaseDate(LocalDate.now())
                                                        .build());
                }

                // Then
                List<Asset> allAssets = assetRepository.findByUserId(testUser.getId());
                assertThat(allAssets).hasSize(5);
                assertThat(allAssets).extracting(Asset::getType).containsExactlyInAnyOrder(physicalTypes);
        }

        @Test
        @DisplayName("Should save all asset conditions correctly")
        void shouldSaveAllAssetConditions() {
                // Given
                AssetCondition[] conditions = {
                                AssetCondition.NEW,
                                AssetCondition.EXCELLENT,
                                AssetCondition.GOOD,
                                AssetCondition.FAIR,
                                AssetCondition.POOR
                };

                // When - save one with each condition
                for (AssetCondition condition : conditions) {
                        assetRepository.save(
                                        Asset.builder()
                                                        .userId(testUser.getId())
                                                        .name("Asset in " + condition.name() + " condition")
                                                        .type(AssetType.ELECTRONICS)
                                                        .condition(condition)
                                                        .quantity(new BigDecimal("1.0"))
                                                        .purchasePrice(new BigDecimal("1000.00"))
                                                        .currentPrice(new BigDecimal("1000.00"))
                                                        .currency("USD")
                                                        .purchaseDate(LocalDate.now())
                                                        .build());
                }

                // Then
                List<Asset> allAssets = assetRepository.findByUserId(testUser.getId());
                assertThat(allAssets).hasSize(5);
                assertThat(allAssets).extracting(Asset::getCondition).containsExactlyInAnyOrder(conditions);
        }

        @Test
        @DisplayName("Should update physical asset fields")
        void shouldUpdatePhysicalAssetFields() {
                // Given - save initial physical asset
                Asset originalAsset = assetRepository.save(
                                Asset.builder()
                                                .userId(testUser.getId())
                                                .name("iPhone 14")
                                                .type(AssetType.ELECTRONICS)
                                                .serialNumber("DLXV9ABC1DEF")
                                                .brand("Apple")
                                                .model("iPhone 14 Pro")
                                                .condition(AssetCondition.GOOD)
                                                .warrantyExpiration(LocalDate.of(2024, 9, 1))
                                                .usefulLifeYears(5)
                                                .quantity(new BigDecimal("1.0"))
                                                .purchasePrice(new BigDecimal("1099.00"))
                                                .currentPrice(new BigDecimal("800.00"))
                                                .currency("USD")
                                                .purchaseDate(LocalDate.of(2023, 9, 1))
                                                .build());

                // When - update condition and warranty
                originalAsset.setCondition(AssetCondition.FAIR);
                originalAsset.setWarrantyExpiration(null); // Expired, removed
                originalAsset.setCurrentPrice(new BigDecimal("700.00")); // Price dropped
                Asset updatedAsset = assetRepository.save(originalAsset);

                // Then
                assertThat(updatedAsset.getCondition()).isEqualTo(AssetCondition.FAIR);
                assertThat(updatedAsset.getWarrantyExpiration()).isNull();
                assertThat(updatedAsset.getCurrentPrice()).isEqualByComparingTo(new BigDecimal("700.00"));
        }

}
