package org.openfinance.repository;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openfinance.entity.Institution;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

/**
 * Integration tests for InstitutionRepository.
 *
 * <p>Uses @DataJpaTest which configures an in-memory H2 database and provides transactional test
 * execution with rollback.
 *
 * <p>Flyway is disabled for these tests - schema is auto-generated by Hibernate.
 *
 * <p>Requirement: Tests for custom queries in InstitutionRepository
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(
        properties = {
            "spring.flyway.enabled=false",
            "spring.jpa.hibernate.ddl-auto=create-drop",
            "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
        })
class InstitutionRepositoryTest {

    @Autowired private InstitutionRepository institutionRepository;

    private Institution systemInstitutionFR;
    private Institution systemInstitutionDE;
    private Institution customInstitutionFR;
    private Institution customInstitutionDE;

    @BeforeEach
    void setUp() {
        // Clear repository before each test
        institutionRepository.deleteAll();

        // Create test institutions
        systemInstitutionFR =
                Institution.builder()
                        .name("BNP Paribas")
                        .bic("BNPAFRPP")
                        .country("FR")
                        .logo("bnp_logo")
                        .isSystem(true)
                        .build();

        systemInstitutionDE =
                Institution.builder()
                        .name("Deutsche Bank")
                        .bic("DEUTDEFF")
                        .country("DE")
                        .logo("db_logo")
                        .isSystem(true)
                        .build();

        customInstitutionFR =
                Institution.builder()
                        .name("My French Bank")
                        .bic("MYFRFRPP")
                        .country("FR")
                        .logo("my_fr_logo")
                        .isSystem(false)
                        .build();

        customInstitutionDE =
                Institution.builder()
                        .name("My German Bank")
                        .bic("MYDEDEFF")
                        .country("DE")
                        .logo("my_de_logo")
                        .isSystem(false)
                        .build();

        // Save all institutions
        institutionRepository.saveAll(
                List.of(
                        systemInstitutionFR,
                        systemInstitutionDE,
                        customInstitutionFR,
                        customInstitutionDE));
    }

    @Test
    void shouldFindAllOrderedByCountryAndName() {
        // When
        List<Institution> result = institutionRepository.findAllByOrderByCountryAscNameAsc();

        // Then
        assertThat(result).hasSize(4);
        // First DE institutions (alphabetically)
        assertThat(result.get(0).getCountry()).isEqualTo("DE");
        assertThat(result.get(0).getName()).isEqualTo("Deutsche Bank");
        assertThat(result.get(1).getCountry()).isEqualTo("DE");
        assertThat(result.get(1).getName()).isEqualTo("My German Bank");
        // Then FR institutions (alphabetically)
        assertThat(result.get(2).getCountry()).isEqualTo("FR");
        assertThat(result.get(2).getName()).isEqualTo("BNP Paribas");
        assertThat(result.get(3).getCountry()).isEqualTo("FR");
        assertThat(result.get(3).getName()).isEqualTo("My French Bank");
    }

    @Test
    void shouldFindByCountryOrderedByName() {
        // When
        List<Institution> frenchInstitutions =
                institutionRepository.findByCountryOrderByNameAsc("FR");

        // Then
        assertThat(frenchInstitutions).hasSize(2);
        assertThat(frenchInstitutions.get(0).getName()).isEqualTo("BNP Paribas");
        assertThat(frenchInstitutions.get(1).getName()).isEqualTo("My French Bank");
        assertThat(frenchInstitutions.get(0).getCountry()).isEqualTo("FR");
        assertThat(frenchInstitutions.get(1).getCountry()).isEqualTo("FR");
    }

    @Test
    void shouldReturnEmptyListForCountryWithNoInstitutions() {
        // When
        List<Institution> result = institutionRepository.findByCountryOrderByNameAsc("IT");

        // Then
        assertThat(result).isEmpty();
    }

    @Test
    void shouldFindSystemInstitutions() {
        // When
        List<Institution> systemInstitutions =
                institutionRepository.findByIsSystemTrueOrderByCountryAscNameAsc();

        // Then
        assertThat(systemInstitutions).hasSize(2);
        assertThat(systemInstitutions.get(0).getName()).isEqualTo("Deutsche Bank");
        assertThat(systemInstitutions.get(1).getName()).isEqualTo("BNP Paribas");
        assertThat(systemInstitutions.get(0).getIsSystem()).isTrue();
        assertThat(systemInstitutions.get(1).getIsSystem()).isTrue();
    }

    @Test
    void shouldFindCustomInstitutions() {
        // When
        List<Institution> customInstitutions =
                institutionRepository.findByIsSystemFalseOrderByNameAsc();

        // Then
        assertThat(customInstitutions).hasSize(2);
        assertThat(customInstitutions.get(0).getName()).isEqualTo("My French Bank");
        assertThat(customInstitutions.get(1).getName()).isEqualTo("My German Bank");
        assertThat(customInstitutions.get(0).getIsSystem()).isFalse();
        assertThat(customInstitutions.get(1).getIsSystem()).isFalse();
    }

    @Test
    void shouldSearchByName() {
        // When
        List<Institution> bnpResults = institutionRepository.searchByName("bnp");

        // Then
        assertThat(bnpResults).hasSize(1);
        assertThat(bnpResults.get(0).getName()).isEqualTo("BNP Paribas");

        // When
        List<Institution> bankResults = institutionRepository.searchByName("bank");

        // Then
        assertThat(bankResults).hasSize(3);
        assertThat(bankResults.stream().map(Institution::getName))
                .containsExactlyInAnyOrder("My French Bank", "My German Bank", "Deutsche Bank");
    }

    @Test
    void shouldReturnEmptyListWhenNoSearchMatches() {
        // When
        List<Institution> result = institutionRepository.searchByName("nonexistent");

        // Then
        assertThat(result).isEmpty();
    }

    @Test
    void shouldFindByCountryAndSearchTerm() {
        // When
        List<Institution> frenchBanks =
                institutionRepository.findByCountryAndSearchTerm("FR", "bank");

        // Then
        assertThat(frenchBanks).hasSize(1);
        assertThat(frenchBanks.get(0).getName()).isEqualTo("My French Bank");
        assertThat(frenchBanks.get(0).getCountry()).isEqualTo("FR");
    }

    @Test
    void shouldFindByBic() {
        // When
        Institution result = institutionRepository.findByBic("BNPAFRPP");

        // Then
        assertThat(result).isNotNull();
        assertThat(result.getName()).isEqualTo("BNP Paribas");
        assertThat(result.getBic()).isEqualTo("BNPAFRPP");
    }

    @Test
    void shouldReturnNullWhenBicNotFound() {
        // When
        Institution result = institutionRepository.findByBic("NONEXISTENT");

        // Then
        assertThat(result).isNull();
    }

    @Test
    void shouldReturnFalseWhenInstitutionNotInUse() {
        // Given - no accounts exist in test
        Long institutionId = systemInstitutionFR.getId();

        // When
        boolean result = institutionRepository.isInUse(institutionId);

        // Then
        assertThat(result).isFalse();
    }

    @Test
    void shouldFindDistinctCountries() {
        // When
        List<String> countries = institutionRepository.findDistinctCountries();

        // Then
        assertThat(countries).containsExactly("DE", "FR");
    }

    @Test
    void shouldReturnEmptyListWhenNoCountries() {
        // Given
        institutionRepository.deleteAll();

        // When
        List<String> countries = institutionRepository.findDistinctCountries();

        // Then
        assertThat(countries).isEmpty();
    }

    @Test
    void shouldSupportFullCrudOperations() {
        // Create
        Institution newInstitution =
                Institution.builder()
                        .name("Test Bank")
                        .bic("TESTFRPP")
                        .country("FR")
                        .isSystem(false)
                        .build();

        Institution saved = institutionRepository.save(newInstitution);
        assertThat(saved.getId()).isNotNull();

        // Read
        Optional<Institution> found = institutionRepository.findById(saved.getId());
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Test Bank");

        // Update
        found.get().setName("Updated Test Bank");
        Institution updated = institutionRepository.save(found.get());
        assertThat(updated.getName()).isEqualTo("Updated Test Bank");

        // Delete
        institutionRepository.delete(updated);
        Optional<Institution> deleted = institutionRepository.findById(updated.getId());
        assertThat(deleted).isNotPresent();
    }

    @Test
    void shouldReturnTrueForExistingInstitution() {
        // When
        boolean exists = institutionRepository.existsById(systemInstitutionFR.getId());

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    void shouldReturnFalseForNonExistingInstitution() {
        // When
        boolean exists = institutionRepository.existsById(999L);

        // Then
        assertThat(exists).isFalse();
    }
}
