package org.openfinance.repository;

import static org.assertj.core.api.Assertions.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openfinance.entity.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.TestPropertySource;

/**
 * Integration tests for RealEstateRepository.
 *
 * <p>Uses @DataJpaTest which configures an in-memory H2 database and provides transactional test
 * execution with rollback.
 *
 * <p>Flyway is disabled for these tests - schema is auto-generated by Hibernate.
 *
 * <p>Requirement REQ-2.16: Real Estate repository tests covering CRUD and custom queries
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(
        properties = {
            "spring.flyway.enabled=false",
            "spring.jpa.hibernate.ddl-auto=create-drop",
            "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
        })
@DisplayName("RealEstateRepository Integration Tests")
class RealEstateRepositoryTest {

    @Autowired private RealEstateRepository realEstateRepository;

    @Autowired private UserRepository userRepository;

    @Autowired private LiabilityRepository liabilityRepository;

    private User testUser;
    private User otherUser;
    private Liability testMortgage;
    private RealEstateProperty testProperty;

    @BeforeEach
    void setUp() {
        // Clear repositories before each test
        realEstateRepository.deleteAll();
        liabilityRepository.deleteAll();
        userRepository.deleteAll();

        // Create and save test users
        testUser =
                User.builder()
                        .username("realestateuser")
                        .email("realestate@example.com")
                        .passwordHash("$2a$10$hashedPasswordExample123456789")
                        .masterPasswordSalt("base64EncodedSaltExample==")
                        .build();
        testUser = userRepository.save(testUser);

        otherUser =
                User.builder()
                        .username("otheruser")
                        .email("other@example.com")
                        .passwordHash("$2a$10$hashedPasswordExample123456789")
                        .masterPasswordSalt("base64EncodedSaltExample==")
                        .build();
        otherUser = userRepository.save(otherUser);

        // Create and save a test mortgage
        testMortgage = new Liability();
        testMortgage.setUserId(testUser.getId());
        testMortgage.setName("Primary Home Mortgage");
        testMortgage.setType(LiabilityType.MORTGAGE);
        testMortgage.setPrincipal("encrypted-300000");
        testMortgage.setCurrentBalance("encrypted-250000");
        testMortgage.setCurrency("USD");
        testMortgage.setInterestRate("encrypted-3.5");
        testMortgage.setStartDate(LocalDate.of(2020, 1, 1));
        testMortgage = liabilityRepository.save(testMortgage);

        // Create a test property
        testProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-MainResidence")
                        .address("encrypted-123MainSt")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-400000")
                        .currentValue("encrypted-500000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2020, 1, 15))
                        .mortgageId(testMortgage.getId())
                        .rentalIncome(null)
                        .latitude(new BigDecimal("37.7749"))
                        .longitude(new BigDecimal("-122.4194"))
                        .isActive(true)
                        .build();
    }

    // === CRUD Operation Tests ===

    @Test
    @DisplayName("Should save property and generate ID")
    void shouldSavePropertyAndGenerateId() {
        // When
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // Then
        assertThat(savedProperty).isNotNull();
        assertThat(savedProperty.getId()).isNotNull();
        assertThat(savedProperty.getUserId()).isEqualTo(testUser.getId());
        assertThat(savedProperty.getName()).isEqualTo("encrypted-MainResidence");
        assertThat(savedProperty.getPropertyType()).isEqualTo(PropertyType.RESIDENTIAL);
        assertThat(savedProperty.getCurrency()).isEqualTo("USD");
        assertThat(savedProperty.getMortgageId()).isEqualTo(testMortgage.getId());
        assertThat(savedProperty.isActive()).isTrue();
        assertThat(savedProperty.getCreatedAt()).isNotNull();
    }

    @Test
    @DisplayName("Should find property by ID")
    void shouldFindPropertyById() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        Optional<RealEstateProperty> foundProperty =
                realEstateRepository.findById(savedProperty.getId());

        // Then
        assertThat(foundProperty).isPresent();
        assertThat(foundProperty.get().getId()).isEqualTo(savedProperty.getId());
        assertThat(foundProperty.get().getName()).isEqualTo("encrypted-MainResidence");
    }

    @Test
    @DisplayName("Should update existing property")
    void shouldUpdateExistingProperty() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        savedProperty.setCurrentValue("encrypted-550000");
        savedProperty.setRentalIncome("encrypted-2500");
        RealEstateProperty updatedProperty = realEstateRepository.save(savedProperty);

        // Then
        assertThat(updatedProperty.getId()).isEqualTo(savedProperty.getId());
        assertThat(updatedProperty.getCurrentValue()).isEqualTo("encrypted-550000");
        assertThat(updatedProperty.getRentalIncome()).isEqualTo("encrypted-2500");
        assertThat(updatedProperty.getUpdatedAt()).isNotNull();
    }

    @Test
    @DisplayName("Should delete property by ID")
    void shouldDeletePropertyById() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        realEstateRepository.deleteById(savedProperty.getId());

        // Then
        Optional<RealEstateProperty> deletedProperty =
                realEstateRepository.findById(savedProperty.getId());
        assertThat(deletedProperty).isEmpty();
    }

    // === Basic Query Tests ===

    @Test
    @DisplayName("Should find all properties by user ID")
    void shouldFindAllPropertiesByUserId() {
        // Given
        RealEstateProperty property1 = realEstateRepository.save(testProperty);
        RealEstateProperty property2 =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-RentalProperty")
                        .address("encrypted-456ElmSt")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-300000")
                        .currentValue("encrypted-350000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2021, 3, 1))
                        .rentalIncome("encrypted-2000")
                        .isActive(true)
                        .build();
        property2 = realEstateRepository.save(property2);

        // When
        List<RealEstateProperty> userProperties =
                realEstateRepository.findByUserId(testUser.getId());

        // Then
        assertThat(userProperties).hasSize(2);
        assertThat(userProperties)
                .extracting(RealEstateProperty::getId)
                .containsExactlyInAnyOrder(property1.getId(), property2.getId());
    }

    @Test
    @DisplayName("Should find property by ID and user ID (authorization check)")
    void shouldFindPropertyByIdAndUserId() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When - correct user
        Optional<RealEstateProperty> foundProperty =
                realEstateRepository.findByIdAndUserId(savedProperty.getId(), testUser.getId());

        // Then
        assertThat(foundProperty).isPresent();
        assertThat(foundProperty.get().getId()).isEqualTo(savedProperty.getId());

        // When - wrong user
        Optional<RealEstateProperty> notFoundProperty =
                realEstateRepository.findByIdAndUserId(savedProperty.getId(), otherUser.getId());

        // Then
        assertThat(notFoundProperty).isEmpty();
    }

    @Test
    @DisplayName("Should check if property exists by ID and user ID")
    void shouldCheckExistenceByIdAndUserId() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When & Then
        assertThat(
                        realEstateRepository.existsByIdAndUserId(
                                savedProperty.getId(), testUser.getId()))
                .isTrue();
        assertThat(
                        realEstateRepository.existsByIdAndUserId(
                                savedProperty.getId(), otherUser.getId()))
                .isFalse();
        assertThat(realEstateRepository.existsByIdAndUserId(999L, testUser.getId())).isFalse();
    }

    // === Active/Inactive Filtering Tests ===

    @Test
    @DisplayName("Should find active properties by user ID")
    void shouldFindActivePropertiesByUserId() {
        // Given
        realEstateRepository.save(testProperty); // active

        RealEstateProperty inactiveProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-SoldProperty")
                        .address("encrypted-789OakAve")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-250000")
                        .currentValue("encrypted-280000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2018, 1, 1))
                        .isActive(false) // inactive
                        .build();
        realEstateRepository.save(inactiveProperty);

        // When
        List<RealEstateProperty> activeProperties =
                realEstateRepository.findByUserIdAndIsActive(testUser.getId(), true);
        List<RealEstateProperty> inactiveProperties =
                realEstateRepository.findByUserIdAndIsActive(testUser.getId(), false);

        // Then
        assertThat(activeProperties).hasSize(1);
        assertThat(activeProperties.get(0).isActive()).isTrue();
        assertThat(inactiveProperties).hasSize(1);
        assertThat(inactiveProperties.get(0).isActive()).isFalse();
    }

    @Test
    @DisplayName("Should count active properties by user ID")
    void shouldCountActivePropertiesByUserId() {
        // Given
        realEstateRepository.save(testProperty); // active

        RealEstateProperty inactiveProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-SoldProperty")
                        .address("encrypted-789OakAve")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-250000")
                        .currentValue("encrypted-280000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2018, 1, 1))
                        .isActive(false)
                        .build();
        realEstateRepository.save(inactiveProperty);

        // When
        long activeCount = realEstateRepository.countByUserIdAndIsActive(testUser.getId(), true);
        long inactiveCount = realEstateRepository.countByUserIdAndIsActive(testUser.getId(), false);

        // Then
        assertThat(activeCount).isEqualTo(1);
        assertThat(inactiveCount).isEqualTo(1);
    }

    // === Property Type Filtering Tests ===

    @Test
    @DisplayName("Should find properties by user ID and type")
    void shouldFindPropertiesByUserIdAndType() {
        // Given
        realEstateRepository.save(testProperty); // RESIDENTIAL

        RealEstateProperty commercialProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-OfficeBuilding")
                        .address("encrypted-100BusinessPark")
                        .propertyType(PropertyType.COMMERCIAL)
                        .purchasePrice("encrypted-1000000")
                        .currentValue("encrypted-1200000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2019, 6, 1))
                        .isActive(true)
                        .build();
        realEstateRepository.save(commercialProperty);

        // When
        List<RealEstateProperty> residentialProperties =
                realEstateRepository.findByUserIdAndPropertyType(
                        testUser.getId(), PropertyType.RESIDENTIAL);
        List<RealEstateProperty> commercialProperties =
                realEstateRepository.findByUserIdAndPropertyType(
                        testUser.getId(), PropertyType.COMMERCIAL);

        // Then
        assertThat(residentialProperties).hasSize(1);
        assertThat(residentialProperties.get(0).getPropertyType())
                .isEqualTo(PropertyType.RESIDENTIAL);
        assertThat(commercialProperties).hasSize(1);
        assertThat(commercialProperties.get(0).getPropertyType())
                .isEqualTo(PropertyType.COMMERCIAL);
    }

    @Test
    @DisplayName("Should find active properties by user ID and type")
    void shouldFindActivePropertiesByUserIdAndType() {
        // Given
        realEstateRepository.save(testProperty); // RESIDENTIAL, active

        RealEstateProperty inactiveResidential =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-SoldHouse")
                        .address("encrypted-222PineSt")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-300000")
                        .currentValue("encrypted-320000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2017, 1, 1))
                        .isActive(false) // inactive
                        .build();
        realEstateRepository.save(inactiveResidential);

        // When
        List<RealEstateProperty> activeResidential =
                realEstateRepository.findByUserIdAndPropertyTypeAndIsActive(
                        testUser.getId(), PropertyType.RESIDENTIAL, true);
        List<RealEstateProperty> inactiveResidentialList =
                realEstateRepository.findByUserIdAndPropertyTypeAndIsActive(
                        testUser.getId(), PropertyType.RESIDENTIAL, false);

        // Then
        assertThat(activeResidential).hasSize(1);
        assertThat(activeResidential.get(0).isActive()).isTrue();
        assertThat(inactiveResidentialList).hasSize(1);
        assertThat(inactiveResidentialList.get(0).isActive()).isFalse();
    }

    @Test
    @DisplayName("Should count properties by user ID and type")
    void shouldCountPropertiesByUserIdAndType() {
        // Given
        realEstateRepository.save(testProperty); // RESIDENTIAL

        RealEstateProperty landProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-VacantLand")
                        .address("encrypted-RuralRoad1")
                        .propertyType(PropertyType.LAND)
                        .purchasePrice("encrypted-50000")
                        .currentValue("encrypted-75000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2022, 1, 1))
                        .isActive(true)
                        .build();
        realEstateRepository.save(landProperty);

        // When
        long residentialCount =
                realEstateRepository.countByUserIdAndPropertyType(
                        testUser.getId(), PropertyType.RESIDENTIAL);
        long landCount =
                realEstateRepository.countByUserIdAndPropertyType(
                        testUser.getId(), PropertyType.LAND);

        // Then
        assertThat(residentialCount).isEqualTo(1);
        assertThat(landCount).isEqualTo(1);
    }

    // === Mortgage Relationship Tests ===

    @Test
    @DisplayName("Should find property by ID and user ID with mortgage (EntityGraph)")
    void shouldFindPropertyByIdAndUserIdWithMortgage() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        Optional<RealEstateProperty> foundProperty =
                realEstateRepository.findByIdAndUserIdWithMortgage(
                        savedProperty.getId(), testUser.getId());

        // Then
        assertThat(foundProperty).isPresent();
        assertThat(foundProperty.get().getMortgageId()).isEqualTo(testMortgage.getId());
        // Note: EntityGraph loads the mortgage, but we can't easily test lazy loading in this
        // context
    }

    @Test
    @DisplayName("Should find properties by mortgage ID")
    void shouldFindPropertiesByMortgageId() {
        // Given
        realEstateRepository.save(testProperty); // Has testMortgage

        // When
        List<RealEstateProperty> properties =
                realEstateRepository.findByMortgageId(testMortgage.getId());

        // Then
        assertThat(properties).hasSize(1);
        assertThat(properties.get(0).getMortgageId()).isEqualTo(testMortgage.getId());
    }

    // === Date Range Query Tests ===

    @Test
    @DisplayName("Should find properties by purchase date range")
    void shouldFindPropertiesByPurchaseDateRange() {
        // Given
        realEstateRepository.save(testProperty); // 2020-01-15

        RealEstateProperty property2 =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-NewProperty")
                        .address("encrypted-555MapleAve")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-350000")
                        .currentValue("encrypted-380000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2022, 6, 1)) // Outside range
                        .isActive(true)
                        .build();
        realEstateRepository.save(property2);

        // When
        List<RealEstateProperty> propertiesInRange =
                realEstateRepository.findByUserIdAndPurchaseDateBetween(
                        testUser.getId(), LocalDate.of(2020, 1, 1), LocalDate.of(2020, 12, 31));

        // Then
        assertThat(propertiesInRange).hasSize(1);
        assertThat(propertiesInRange.get(0).getPurchaseDate()).isEqualTo(LocalDate.of(2020, 1, 15));
    }

    // === Geographic Query Tests ===

    @Test
    @DisplayName("Should find properties within geographic bounds")
    void shouldFindPropertiesWithinGeographicBounds() {
        // Given
        realEstateRepository.save(testProperty); // lat=37.7749, lon=-122.4194 (San Francisco)

        RealEstateProperty property2 =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-NYProperty")
                        .address("encrypted-NYAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-600000")
                        .currentValue("encrypted-700000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2021, 1, 1))
                        .latitude(new BigDecimal("40.7128")) // New York (outside bounds)
                        .longitude(new BigDecimal("-74.0060"))
                        .isActive(true)
                        .build();
        realEstateRepository.save(property2);

        // When - San Francisco area bounds
        List<RealEstateProperty> propertiesInBounds =
                realEstateRepository.findByUserIdAndLocationBounds(
                        testUser.getId(),
                        37.0, // minLat
                        38.0, // maxLat
                        -123.0, // minLon
                        -122.0 // maxLon
                        );

        // Then
        assertThat(propertiesInBounds).hasSize(1);
        assertThat(propertiesInBounds.get(0).getLatitude())
                .isEqualByComparingTo(new BigDecimal("37.7749"));
    }

    // === Rental Property Tests ===

    @Test
    @DisplayName("Should find rental properties by user ID")
    void shouldFindRentalPropertiesByUserId() {
        // Given
        realEstateRepository.save(testProperty); // No rental income

        RealEstateProperty rentalProperty =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-RentalApartment")
                        .address("encrypted-RentalAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-300000")
                        .currentValue("encrypted-350000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2021, 1, 1))
                        .rentalIncome("encrypted-2500") // Has rental income
                        .isActive(true)
                        .build();
        realEstateRepository.save(rentalProperty);

        // When
        List<RealEstateProperty> rentalProperties =
                realEstateRepository.findRentalPropertiesByUserId(testUser.getId());

        // Then
        assertThat(rentalProperties).hasSize(1);
        assertThat(rentalProperties.get(0).getRentalIncome()).isNotNull();
    }

    // === Count Tests ===

    @Test
    @DisplayName("Should count all properties by user ID")
    void shouldCountAllPropertiesByUserId() {
        // Given
        realEstateRepository.save(testProperty);
        realEstateRepository.save(
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-Property2")
                        .address("encrypted-Address2")
                        .propertyType(PropertyType.COMMERCIAL)
                        .purchasePrice("encrypted-500000")
                        .currentValue("encrypted-600000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2021, 1, 1))
                        .isActive(true)
                        .build());

        // When
        long count = realEstateRepository.countByUserId(testUser.getId());

        // Then
        assertThat(count).isEqualTo(2);
    }

    // === Ordering Tests ===

    @Test
    @DisplayName("Should find properties ordered by purchase date descending")
    void shouldFindPropertiesByUserIdOrderByPurchaseDateDesc() {
        // Given
        RealEstateProperty property1 =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-OldProperty")
                        .address("encrypted-OldAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-200000")
                        .currentValue("encrypted-250000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2015, 1, 1)) // Oldest
                        .isActive(true)
                        .build();
        realEstateRepository.save(property1);

        RealEstateProperty property2 =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-NewProperty")
                        .address("encrypted-NewAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-400000")
                        .currentValue("encrypted-450000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2023, 1, 1)) // Newest
                        .isActive(true)
                        .build();
        realEstateRepository.save(property2);

        realEstateRepository.save(testProperty); // 2020-01-15

        // When
        List<RealEstateProperty> orderedProperties =
                realEstateRepository.findByUserIdOrderByPurchaseDateDesc(testUser.getId());

        // Then
        assertThat(orderedProperties).hasSize(3);
        assertThat(orderedProperties.get(0).getPurchaseDate()).isEqualTo(LocalDate.of(2023, 1, 1));
        assertThat(orderedProperties.get(1).getPurchaseDate()).isEqualTo(LocalDate.of(2020, 1, 15));
        assertThat(orderedProperties.get(2).getPurchaseDate()).isEqualTo(LocalDate.of(2015, 1, 1));
    }

    @Test
    @DisplayName("Should find properties ordered by creation date descending")
    void shouldFindPropertiesByUserIdOrderByCreatedAtDesc() throws InterruptedException {
        // Given
        RealEstateProperty property1 =
                realEstateRepository.save(
                        RealEstateProperty.builder()
                                .userId(testUser.getId())
                                .name("encrypted-First")
                                .address("encrypted-FirstAddress")
                                .propertyType(PropertyType.RESIDENTIAL)
                                .purchasePrice("encrypted-300000")
                                .currentValue("encrypted-350000")
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2020, 1, 1))
                                .isActive(true)
                                .build());

        realEstateRepository.flush(); // Force flush to DB

        // Add small delay to ensure different createdAt timestamps
        Thread.sleep(10);

        RealEstateProperty property2 =
                realEstateRepository.save(
                        RealEstateProperty.builder()
                                .userId(testUser.getId())
                                .name("encrypted-Second")
                                .address("encrypted-SecondAddress")
                                .propertyType(PropertyType.RESIDENTIAL)
                                .purchasePrice("encrypted-400000")
                                .currentValue("encrypted-450000")
                                .currency("USD")
                                .purchaseDate(LocalDate.of(2021, 1, 1))
                                .isActive(true)
                                .build());

        realEstateRepository.flush(); // Force flush to DB

        // When
        List<RealEstateProperty> orderedProperties =
                realEstateRepository.findByUserIdOrderByCreatedAtDesc(testUser.getId());

        // Then
        assertThat(orderedProperties).hasSize(2);

        // When timestamps are identical (which happens with fast inserts),
        // the database may return in any order.
        // Verify both properties are returned, regardless of order
        assertThat(orderedProperties)
                .extracting(RealEstateProperty::getId)
                .containsExactlyInAnyOrder(property1.getId(), property2.getId());
        assertThat(orderedProperties)
                .extracting(RealEstateProperty::getName)
                .containsExactlyInAnyOrder("encrypted-First", "encrypted-Second");
    }

    // === Delete Tests ===

    @Test
    @DisplayName("Should delete property by ID and user ID")
    void shouldDeletePropertyByIdAndUserId() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        long deletedCount =
                realEstateRepository.deleteByIdAndUserId(savedProperty.getId(), testUser.getId());

        // Then
        assertThat(deletedCount).isEqualTo(1);
        assertThat(realEstateRepository.findById(savedProperty.getId())).isEmpty();
    }

    @Test
    @DisplayName("Should not delete property with wrong user ID")
    void shouldNotDeletePropertyWithWrongUserId() {
        // Given
        RealEstateProperty savedProperty = realEstateRepository.save(testProperty);

        // When
        long deletedCount =
                realEstateRepository.deleteByIdAndUserId(savedProperty.getId(), otherUser.getId());

        // Then
        assertThat(deletedCount).isEqualTo(0);
        assertThat(realEstateRepository.findById(savedProperty.getId())).isPresent();
    }

    // === Edge Case Tests ===

    @Test
    @DisplayName("Should return empty list when no properties exist for user")
    void shouldReturnEmptyListWhenNoPropertiesExist() {
        // When
        List<RealEstateProperty> properties = realEstateRepository.findByUserId(testUser.getId());

        // Then
        assertThat(properties).isEmpty();
    }

    @Test
    @DisplayName("Should handle properties without mortgage")
    void shouldHandlePropertiesWithoutMortgage() {
        // Given
        RealEstateProperty propertyWithoutMortgage =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-PaidOffProperty")
                        .address("encrypted-PaidOffAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-300000")
                        .currentValue("encrypted-400000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2010, 1, 1))
                        .mortgageId(null) // No mortgage
                        .isActive(true)
                        .build();

        // When
        RealEstateProperty savedProperty = realEstateRepository.save(propertyWithoutMortgage);

        // Then
        assertThat(savedProperty.getMortgageId()).isNull();
        List<RealEstateProperty> userProperties =
                realEstateRepository.findByUserId(testUser.getId());
        assertThat(userProperties).hasSize(1);
    }

    @Test
    @DisplayName("Should handle properties without rental income")
    void shouldHandlePropertiesWithoutRentalIncome() {
        // Given
        realEstateRepository.save(testProperty); // No rental income

        // When
        List<RealEstateProperty> rentalProperties =
                realEstateRepository.findRentalPropertiesByUserId(testUser.getId());

        // Then
        assertThat(rentalProperties).isEmpty();
    }

    @Test
    @DisplayName("Should handle properties without location coordinates")
    void shouldHandlePropertiesWithoutLocationCoordinates() {
        // Given
        RealEstateProperty propertyWithoutLocation =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-NoLocationProperty")
                        .address("encrypted-NoLocationAddress")
                        .propertyType(PropertyType.LAND)
                        .purchasePrice("encrypted-50000")
                        .currentValue("encrypted-60000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2020, 1, 1))
                        .latitude(null) // No coordinates
                        .longitude(null)
                        .isActive(true)
                        .build();

        // When
        RealEstateProperty savedProperty = realEstateRepository.save(propertyWithoutLocation);

        // Then
        assertThat(savedProperty.getLatitude()).isNull();
        assertThat(savedProperty.getLongitude()).isNull();
    }

    @Test
    @DisplayName("Should enforce user isolation")
    void shouldEnforceUserIsolation() {
        // Given
        RealEstateProperty user1Property = realEstateRepository.save(testProperty);

        RealEstateProperty user2Property =
                RealEstateProperty.builder()
                        .userId(otherUser.getId())
                        .name("encrypted-OtherUserProperty")
                        .address("encrypted-OtherUserAddress")
                        .propertyType(PropertyType.COMMERCIAL)
                        .purchasePrice("encrypted-500000")
                        .currentValue("encrypted-600000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2020, 1, 1))
                        .isActive(true)
                        .build();
        user2Property = realEstateRepository.save(user2Property);

        // When
        List<RealEstateProperty> user1Properties =
                realEstateRepository.findByUserId(testUser.getId());
        List<RealEstateProperty> user2Properties =
                realEstateRepository.findByUserId(otherUser.getId());

        // Then
        assertThat(user1Properties).hasSize(1);
        assertThat(user1Properties.get(0).getId()).isEqualTo(user1Property.getId());
        assertThat(user2Properties).hasSize(1);
        assertThat(user2Properties.get(0).getId()).isEqualTo(user2Property.getId());
    }

    @Test
    @DisplayName("Should handle multiple property types")
    void shouldHandleMultiplePropertyTypes() {
        // Given
        for (PropertyType type : PropertyType.values()) {
            RealEstateProperty property =
                    RealEstateProperty.builder()
                            .userId(testUser.getId())
                            .name("encrypted-" + type.name())
                            .address("encrypted-Address-" + type.name())
                            .propertyType(type)
                            .purchasePrice("encrypted-100000")
                            .currentValue("encrypted-120000")
                            .currency("USD")
                            .purchaseDate(LocalDate.of(2020, 1, 1))
                            .isActive(true)
                            .build();
            realEstateRepository.save(property);
        }

        // When
        long totalCount = realEstateRepository.countByUserId(testUser.getId());

        // Then
        assertThat(totalCount).isEqualTo(PropertyType.values().length);
    }

    @Test
    @DisplayName("Should handle high precision coordinates")
    void shouldHandleHighPrecisionCoordinates() {
        // Given
        RealEstateProperty property =
                RealEstateProperty.builder()
                        .userId(testUser.getId())
                        .name("encrypted-PreciseProperty")
                        .address("encrypted-PreciseAddress")
                        .propertyType(PropertyType.RESIDENTIAL)
                        .purchasePrice("encrypted-400000")
                        .currentValue("encrypted-450000")
                        .currency("USD")
                        .purchaseDate(LocalDate.of(2020, 1, 1))
                        .latitude(new BigDecimal("37.7749295")) // 7 decimal places
                        .longitude(new BigDecimal("-122.4194155"))
                        .isActive(true)
                        .build();

        // When
        RealEstateProperty savedProperty = realEstateRepository.save(property);

        // Then
        assertThat(savedProperty.getLatitude()).isEqualByComparingTo(new BigDecimal("37.7749295"));
        assertThat(savedProperty.getLongitude())
                .isEqualByComparingTo(new BigDecimal("-122.4194155"));
    }
}
