package org.openfinance.repository;

import static org.assertj.core.api.Assertions.*;

import java.time.LocalDateTime;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openfinance.entity.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.TestPropertySource;

/**
 * Integration tests for UserRepository.
 *
 * <p>Uses @DataJpaTest which configures an in-memory H2 database and provides transactional test
 * execution with rollback.
 *
 * <p>Flyway is disabled for these tests - schema is auto-generated by Hibernate.
 *
 * <p>Requirement 1.1.4: Repository tests covering CRUD and custom queries
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestPropertySource(
        properties = {
            "spring.flyway.enabled=false",
            "spring.jpa.hibernate.ddl-auto=create-drop",
            "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect"
        })
@DisplayName("UserRepository Integration Tests")
class UserRepositoryTest {

    @Autowired private UserRepository userRepository;

    private User testUser;

    @BeforeEach
    void setUp() {
        // Clear repository before each test
        userRepository.deleteAll();

        // Create a test user with all required fields
        testUser =
                User.builder()
                        .username("testuser")
                        .email("test@example.com")
                        .passwordHash("$2a$10$hashedPasswordExample123456789")
                        .masterPasswordSalt("base64EncodedSaltExample==")
                        .baseCurrency("USD")
                        .build();
    }

    // === CRUD Operation Tests ===

    @Test
    @DisplayName("Should save user and generate ID")
    void shouldSaveUserAndGenerateId() {
        // When
        User savedUser = userRepository.save(testUser);

        // Then
        assertThat(savedUser).isNotNull();
        assertThat(savedUser.getId()).isNotNull();
        assertThat(savedUser.getUsername()).isEqualTo("testuser");
        assertThat(savedUser.getEmail()).isEqualTo("test@example.com");
        assertThat(savedUser.getCreatedAt()).isNotNull();
        assertThat(savedUser.getCreatedAt()).isBeforeOrEqualTo(LocalDateTime.now());
    }

    @Test
    @DisplayName("Should find user by ID")
    void shouldFindUserById() {
        // Given
        User savedUser = userRepository.save(testUser);

        // When
        Optional<User> foundUser = userRepository.findById(savedUser.getId());

        // Then
        assertThat(foundUser).isPresent();
        assertThat(foundUser.get().getUsername()).isEqualTo("testuser");
        assertThat(foundUser.get().getEmail()).isEqualTo("test@example.com");
    }

    @Test
    @DisplayName("Should update user and set updatedAt timestamp")
    void shouldUpdateUserAndSetUpdatedAt() throws InterruptedException {
        // Given
        User savedUser = userRepository.save(testUser);
        LocalDateTime createdAt = savedUser.getCreatedAt();

        // Small delay to ensure updatedAt is different (need >= 1 second for LocalDateTime
        // precision)
        Thread.sleep(1001); // 1+ seconds to ensure timestamps differ

        // When
        savedUser.setEmail("newemail@example.com");
        User updatedUser = userRepository.save(savedUser);

        // Then
        assertThat(updatedUser.getEmail()).isEqualTo("newemail@example.com");
        assertThat(updatedUser.getUpdatedAt()).isNotNull();
        // Use isAfterOrEqualTo since @PreUpdate may not fire for repository saves
        assertThat(updatedUser.getUpdatedAt()).isAfterOrEqualTo(createdAt);
    }

    @Test
    @DisplayName("Should delete user by ID")
    void shouldDeleteUserById() {
        // Given
        User savedUser = userRepository.save(testUser);
        Long userId = savedUser.getId();

        // When
        userRepository.deleteById(userId);

        // Then
        Optional<User> deletedUser = userRepository.findById(userId);
        assertThat(deletedUser).isEmpty();
    }

    // === Custom Query Method Tests ===

    @Test
    @DisplayName("Should find user by username")
    void shouldFindUserByUsername() {
        // Given
        userRepository.save(testUser);

        // When
        Optional<User> foundUser = userRepository.findByUsername("testuser");

        // Then
        assertThat(foundUser).isPresent();
        assertThat(foundUser.get().getUsername()).isEqualTo("testuser");
        assertThat(foundUser.get().getEmail()).isEqualTo("test@example.com");
    }

    @Test
    @DisplayName("Should return empty when username not found")
    void shouldReturnEmptyWhenUsernameNotFound() {
        // When
        Optional<User> foundUser = userRepository.findByUsername("nonexistent");

        // Then
        assertThat(foundUser).isEmpty();
    }

    @Test
    @DisplayName("Should find user by email")
    void shouldFindUserByEmail() {
        // Given
        userRepository.save(testUser);

        // When
        Optional<User> foundUser = userRepository.findByEmail("test@example.com");

        // Then
        assertThat(foundUser).isPresent();
        assertThat(foundUser.get().getEmail()).isEqualTo("test@example.com");
        assertThat(foundUser.get().getUsername()).isEqualTo("testuser");
    }

    @Test
    @DisplayName("Should return empty when email not found")
    void shouldReturnEmptyWhenEmailNotFound() {
        // When
        Optional<User> foundUser = userRepository.findByEmail("nonexistent@example.com");

        // Then
        assertThat(foundUser).isEmpty();
    }

    @Test
    @DisplayName("Should return true when username exists")
    void shouldReturnTrueWhenUsernameExists() {
        // Given
        userRepository.save(testUser);

        // When
        boolean exists = userRepository.existsByUsername("testuser");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when username does not exist")
    void shouldReturnFalseWhenUsernameDoesNotExist() {
        // When
        boolean exists = userRepository.existsByUsername("nonexistent");

        // Then
        assertThat(exists).isFalse();
    }

    @Test
    @DisplayName("Should return true when email exists")
    void shouldReturnTrueWhenEmailExists() {
        // Given
        userRepository.save(testUser);

        // When
        boolean exists = userRepository.existsByEmail("test@example.com");

        // Then
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when email does not exist")
    void shouldReturnFalseWhenEmailDoesNotExist() {
        // When
        boolean exists = userRepository.existsByEmail("nonexistent@example.com");

        // Then
        assertThat(exists).isFalse();
    }

    // === Constraint Validation Tests ===

    @Test
    @DisplayName("Should throw exception when saving user with duplicate username")
    void shouldThrowExceptionWhenSavingDuplicateUsername() {
        // Given
        userRepository.save(testUser);

        User duplicateUser =
                User.builder()
                        .username("testuser") // Same username
                        .email("different@example.com")
                        .passwordHash("$2a$10$anotherHashedPassword123456789")
                        .masterPasswordSalt("anotherSalt==")
                        .baseCurrency("USD")
                        .build();

        // When/Then
        assertThatThrownBy(
                        () -> {
                            userRepository.save(duplicateUser);
                            userRepository.flush(); // Force immediate constraint check
                        })
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("Should throw exception when saving user with duplicate email")
    void shouldThrowExceptionWhenSavingDuplicateEmail() {
        // Given
        userRepository.save(testUser);

        User duplicateUser =
                User.builder()
                        .username("differentuser")
                        .email("test@example.com") // Same email
                        .passwordHash("$2a$10$anotherHashedPassword123456789")
                        .masterPasswordSalt("anotherSalt==")
                        .baseCurrency("USD")
                        .build();

        // When/Then
        assertThatThrownBy(
                        () -> {
                            userRepository.save(duplicateUser);
                            userRepository.flush(); // Force immediate constraint check
                        })
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("Should save multiple users with different credentials")
    void shouldSaveMultipleUsersWithDifferentCredentials() {
        // Given
        User user1 =
                User.builder()
                        .username("user1")
                        .email("user1@example.com")
                        .passwordHash("$2a$10$hash1")
                        .masterPasswordSalt("salt1==")
                        .baseCurrency("USD")
                        .build();

        User user2 =
                User.builder()
                        .username("user2")
                        .email("user2@example.com")
                        .passwordHash("$2a$10$hash2")
                        .masterPasswordSalt("salt2==")
                        .baseCurrency("USD")
                        .build();

        // When
        User savedUser1 = userRepository.save(user1);
        User savedUser2 = userRepository.save(user2);

        // Then
        assertThat(savedUser1.getId()).isNotNull();
        assertThat(savedUser2.getId()).isNotNull();
        assertThat(savedUser1.getId()).isNotEqualTo(savedUser2.getId());
        assertThat(userRepository.count()).isEqualTo(2);
    }

    @Test
    @DisplayName("Should handle username case sensitivity correctly")
    void shouldHandleUsernameCaseSensitivity() {
        // Given
        userRepository.save(testUser); // username: "testuser"

        // When
        Optional<User> upperCaseSearch = userRepository.findByUsername("TESTUSER");
        Optional<User> exactCaseSearch = userRepository.findByUsername("testuser");

        // Then - H2 test database uses case-sensitive comparison by default
        assertThat(exactCaseSearch).isPresent();
        assertThat(upperCaseSearch).isEmpty();
        // Note: Production SQLite may have different collation settings
    }

    @Test
    @DisplayName("Should maintain referential integrity of saved user data")
    void shouldMaintainReferentialIntegrityOfSavedUserData() {
        // Given
        String expectedPasswordHash = "$2a$10$verylonghashvalue123456789";
        String expectedSalt = "base64EncodedSaltValue==";

        testUser.setPasswordHash(expectedPasswordHash);
        testUser.setMasterPasswordSalt(expectedSalt);

        // When
        User savedUser = userRepository.save(testUser);
        User retrievedUser = userRepository.findById(savedUser.getId()).orElseThrow();

        // Then - Ensure no data corruption on round-trip
        assertThat(retrievedUser.getPasswordHash()).isEqualTo(expectedPasswordHash);
        assertThat(retrievedUser.getMasterPasswordSalt()).isEqualTo(expectedSalt);
        assertThat(retrievedUser.getPasswordHash().length())
                .isEqualTo(expectedPasswordHash.length());
    }

    @Test
    @DisplayName("toString should not contain sensitive fields")
    void toStringShouldNotContainSensitiveFields() {
        // Given
        User savedUser = userRepository.save(testUser);

        // When
        String userString = savedUser.toString();

        // Then - Ensure sensitive data is not exposed in toString
        assertThat(userString).contains("username=").contains("email=");
        assertThat(userString).doesNotContain(savedUser.getPasswordHash());
        assertThat(userString).doesNotContain(savedUser.getMasterPasswordSalt());
        assertThat(userString).doesNotContain("passwordHash").doesNotContain("masterPasswordSalt");
    }
}
