-- Domain records accept the same 3..10 character symbols as the currency catalog.
ALTER TABLE accounts DROP CONSTRAINT chk_currency;
ALTER TABLE accounts ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE accounts ADD CONSTRAINT chk_currency CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE assets DROP CONSTRAINT chk_asset_currency_length;
ALTER TABLE assets ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE assets ADD CONSTRAINT chk_asset_currency_length CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE liabilities DROP CONSTRAINT chk_liability_currency_length;
ALTER TABLE liabilities ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE liabilities ADD CONSTRAINT chk_liability_currency_length CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE liability_tranches DROP CONSTRAINT chk_tranche_currency_length;
ALTER TABLE liability_tranches ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE liability_tranches ADD CONSTRAINT chk_tranche_currency_length CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE real_estate_properties DROP CONSTRAINT chk_real_estate_currency_length;
ALTER TABLE real_estate_properties ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE real_estate_properties ADD CONSTRAINT chk_real_estate_currency_length CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE transactions DROP CONSTRAINT transactions_currency_check;
ALTER TABLE transactions ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE transactions ADD CONSTRAINT transactions_currency_check CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE recurring_transactions DROP CONSTRAINT recurring_transactions_currency_check;
ALTER TABLE recurring_transactions ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE recurring_transactions ADD CONSTRAINT recurring_transactions_currency_check CHECK (LENGTH(currency) BETWEEN 3 AND 10);
ALTER TABLE transactions ALTER COLUMN original_currency TYPE VARCHAR(10);
ALTER TABLE transactions ALTER COLUMN account_currency TYPE VARCHAR(10);
ALTER TABLE transactions_archive ALTER COLUMN currency TYPE VARCHAR(10);
ALTER TABLE transactions_archive ALTER COLUMN original_currency TYPE VARCHAR(10);
ALTER TABLE transactions_archive ALTER COLUMN account_currency TYPE VARCHAR(10);
ALTER TABLE account_currency_changes ALTER COLUMN from_currency TYPE VARCHAR(10);
ALTER TABLE account_currency_changes ALTER COLUMN to_currency TYPE VARCHAR(10);
ALTER TABLE real_estate_value_history ALTER COLUMN currency TYPE VARCHAR(10);
