package org.openfinance.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.openfinance.entity.PropertyType;

/**
 * Data Transfer Object for real estate property responses.
 *
 * <p>This DTO is returned to clients when retrieving property information. It contains decrypted
 * values, excludes sensitive internal fields, and includes calculated fields for financial
 * analysis.
 *
 * <p>Requirement REQ-2.16.1: Users can view their property information
 *
 * <p>Requirement REQ-2.16.2: Display property equity, ROI, and appreciation
 *
 * @see org.openfinance.entity.RealEstateProperty
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RealEstatePropertyResponse {

    /** Unique identifier of the property. */
    private Long id;

    /** ID of the user who owns this property. */
    private Long userId;

    /**
     * Name or description of the property (decrypted).
     *
     * <p>Requirement REQ-2.16.1: Display property name
     */
    private String name;

    /**
     * Type of property (RESIDENTIAL, COMMERCIAL, LAND, MIXED_USE, INDUSTRIAL, OTHER).
     *
     * <p>Requirement REQ-2.16.1: Property type categorization
     */
    private PropertyType propertyType;

    /**
     * Physical address of the property (decrypted).
     *
     * <p>Requirement REQ-2.16.1: Display property address
     */
    private String address;

    /**
     * Original purchase price of the property (decrypted).
     *
     * <p>Requirement REQ-2.16.2: Display purchase price
     */
    private BigDecimal purchasePrice;

    /**
     * Current estimated market value of the property (decrypted).
     *
     * <p>Requirement REQ-2.16.1: Display current value
     */
    private BigDecimal currentValue;

    /** Date when the property was purchased. */
    private LocalDate purchaseDate;

    /**
     * Currency code in ISO 4217 format.
     *
     * <p>Requirement REQ-2.16.3: Multi-currency support
     */
    private String currency;

    /**
     * ID of the mortgage liability associated with this property.
     *
     * <p>Null if the property has no mortgage.
     */
    private Long mortgageId;

    /**
     * Name of the mortgage (if linked).
     *
     * <p>For display purposes. Null if no mortgage is linked.
     */
    private String mortgageName;

    /**
     * Monthly rental income generated by this property (decrypted).
     *
     * <p>Null for non-rental properties.
     *
     * <p>Requirement REQ-2.16.2: Display rental income
     */
    private BigDecimal rentalIncome;

    /** Latitude coordinate for mapping. */
    private BigDecimal latitude;

    /** Longitude coordinate for mapping. */
    private BigDecimal longitude;

    /** Whether the property is currently active/owned. */
    @com.fasterxml.jackson.annotation.JsonProperty("isActive")
    private boolean isActive;

    /** Optional notes about the property (decrypted). */
    private String notes;

    /** Optional JSON array of document references (decrypted). */
    private String documents;

    /** Timestamp when the property record was created. */
    private LocalDateTime createdAt;

    /** Timestamp when the property record was last modified. */
    private LocalDateTime updatedAt;

    // === Calculated Fields ===

    /**
     * Total appreciation amount (currentValue - purchasePrice).
     *
     * <p><strong>Calculated field</strong> - computed from purchase and current values.
     *
     * <p>Positive values indicate appreciation, negative indicate depreciation.
     *
     * <p>Requirement REQ-2.16.2: Display property appreciation
     */
    private BigDecimal appreciation;

    /**
     * Appreciation percentage ((appreciation / purchasePrice) * 100).
     *
     * <p><strong>Calculated field</strong> - expressed as percentage.
     *
     * <p>Example: 15.5 represents 15.5% appreciation
     *
     * <p>Requirement REQ-2.16.2: Display appreciation rate
     */
    private BigDecimal appreciationPercentage;

    /**
     * Annual rental yield percentage ((rentalIncome * 12 / currentValue) * 100).
     *
     * <p><strong>Calculated field</strong> - annual return from rental income.
     *
     * <p>Null for non-rental properties or if rentalIncome is not specified.
     *
     * <p>Requirement REQ-2.16.2: Display rental yield
     */
    private BigDecimal rentalYield;

    /**
     * Property equity (currentValue - mortgage balance).
     *
     * <p><strong>Calculated field</strong> - requires linked mortgage for accurate calculation.
     *
     * <p>If no mortgage is linked, equity equals currentValue.
     *
     * <p>Requirement REQ-2.16.2: Display property equity
     */
    private BigDecimal equity;

    /**
     * Equity percentage ((equity / currentValue) * 100).
     *
     * <p><strong>Calculated field</strong> - percentage of property owned outright.
     *
     * <p>Example: 35.5 represents 35.5% equity, meaning 64.5% is financed.
     *
     * <p>Requirement REQ-2.16.2: Display equity percentage
     */
    private BigDecimal equityPercentage;

    /**
     * Outstanding mortgage balance (if applicable).
     *
     * <p><strong>Calculated field</strong> - from linked mortgage liability.
     *
     * <p>Null if no mortgage is linked or mortgage data unavailable.
     */
    private BigDecimal mortgageBalance;

    /**
     * Number of years since purchase.
     *
     * <p><strong>Calculated field</strong> - computed from purchase date to current date.
     *
     * <p>Useful for tracking holding period.
     */
    private Long yearsOwned;

    /**
     * Return on Investment percentage.
     *
     * <p><strong>Calculated field</strong> - considers appreciation and rental income.
     *
     * <p>Formula: ((currentValue - purchasePrice + totalRentalIncome) / purchasePrice) * 100
     *
     * <p>Requirement REQ-2.16.2: Display property ROI
     */
    private BigDecimal roi;

    // === Currency Conversion Fields (Requirement REQ-2.4) ===

    /**
     * Current property value ({@code currentValue}) converted to the user's base currency.
     *
     * <p>Populated only when the property currency differs from the user's base currency and a
     * valid exchange rate is available. Falls back to {@code currentValue} otherwise.
     *
     * <p>Requirement REQ-2.4: Conversion metadata for base-currency display
     */
    private BigDecimal valueInBaseCurrency;

    /**
     * The user's base currency (ISO 4217) at the time this response was built.
     *
     * <p>Requirement REQ-2.4: Base currency reference
     */
    private String baseCurrency;

    /**
     * Exchange rate used to convert {@code currentValue} to {@code valueInBaseCurrency}.
     *
     * <p>Represents: 1 unit of {@code currency} = {@code exchangeRate} units of {@code
     * baseCurrency}. Null when no conversion was performed.
     *
     * <p>Requirement REQ-2.6: Exchange rate used for conversion
     */
    private BigDecimal exchangeRate;

    /**
     * Whether the value has been converted from a foreign currency to the base currency.
     *
     * <p>{@code true} only when {@code currency != baseCurrency} AND conversion succeeded.
     *
     * <p>Requirement REQ-3.6: isConverted flag semantics
     */
    private Boolean isConverted;

    // === Secondary Currency Conversion Fields (Requirement REQ-3.4, REQ-3.5) ===

    /**
     * Current property value converted to the user's optional secondary currency.
     *
     * <p>Populated only when the user has a secondary currency configured AND the property currency
     * differs from the secondary currency AND a valid exchange rate is available. Null otherwise.
     *
     * <p>Requirement REQ-3.4, REQ-3.5: Secondary conversion metadata
     */
    private BigDecimal valueInSecondaryCurrency;

    /**
     * The user's secondary currency (ISO 4217) at the time this response was built. Echoed from
     * user settings. Null when no secondary currency is configured.
     *
     * <p>Requirement REQ-3.4: Secondary currency reference
     */
    private String secondaryCurrency;

    /**
     * Exchange rate used to convert {@code currentValue} to {@code valueInSecondaryCurrency}.
     *
     * <p>Represents: 1 unit of {@code currency} = {@code secondaryExchangeRate} units of {@code
     * secondaryCurrency}. Null when no secondary conversion was performed.
     *
     * <p>Requirement REQ-3.7: Secondary exchange rate
     */
    private BigDecimal secondaryExchangeRate;
}
