package org.openfinance.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.openfinance.converter.EncryptedStringConverter;

/**
 * Entity representing an AI-generated financial insight or recommendation for a user.
 *
 * <p>Insights are automatically generated by analyzing user's financial data including:
 *
 * <ul>
 *   <li>Spending patterns and trends
 *   <li>Unusual or suspicious transactions
 *   <li>Budget performance and recommendations
 *   <li>Savings opportunities and optimization tips
 * </ul>
 *
 * <p>Each insight has a type, priority level, and can be dismissed by the user.
 *
 * <p><strong>Example Insights:</strong>
 *
 * <pre>
 * Type: SPENDING_ANOMALY
 * Title: "Unusual Spending Detected"
 * Description: "Your restaurant spending is 45% higher than last month ($520 vs $360)"
 *
 * Type: BUDGET_WARNING
 * Title: "Budget Limit Approaching"
 * Description: "You've spent 85% of your grocery budget for this month"
 *
 * Type: SAVINGS_OPPORTUNITY
 * Title: "Subscription Optimization"
 * Description: "You have 3 streaming services costing $45/month. Consider consolidating."
 * </pre>
 *
 * @see InsightType
 * @see InsightPriority
 * @since Sprint 11 - AI Assistant Integration (Task 11.4)
 */
@Entity
@Table(
        name = "insights",
        indexes = {
            @Index(name = "idx_insight_user_id", columnList = "user_id"),
            @Index(name = "idx_insight_created_at", columnList = "created_at DESC"),
            @Index(name = "idx_insight_priority", columnList = "priority"),
            @Index(name = "idx_insight_dismissed", columnList = "dismissed")
        })
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Insight {

    /** Primary key. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user who owns this insight.
     *
     * <p>Required field. Insight is deleted when user is deleted (cascade).
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Type of insight (spending anomaly, budget warning, savings opportunity, etc.).
     *
     * <p>Stored as VARCHAR(50) in database.
     *
     * @see InsightType
     */
    @NotNull(message = "Insight type is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 50)
    private InsightType type;

    /**
     * Brief title summarizing the insight (max 200 characters).
     *
     * <p>Examples: "Unusual Spending Detected", "Budget Limit Approaching"
     */
    @NotBlank(message = "Insight title is required")
    @Size(max = 200, message = "Title must be at most 200 characters")
    @Column(name = "title", nullable = false, length = 512)
    @Convert(converter = EncryptedStringConverter.class)
    private String title;

    /**
     * Detailed description explaining the insight and providing context.
     *
     * <p>May include specific numbers, comparisons, and actionable recommendations. Stored as TEXT
     * to support longer descriptions.
     */
    @NotBlank(message = "Insight description is required")
    @Size(max = 2000, message = "Description must be at most 2000 characters")
    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    @Convert(converter = EncryptedStringConverter.class)
    private String description;

    /**
     * Priority level indicating urgency/importance.
     *
     * <p>HIGH: Requires immediate attention (e.g., budget exceeded, unusual activity) MEDIUM:
     * Important but not urgent (e.g., savings opportunity, trend notification) LOW: Informational
     * (e.g., monthly summary, general tips)
     *
     * @see InsightPriority
     */
    @NotNull(message = "Insight priority is required")
    @Enumerated(EnumType.STRING)
    @Column(name = "priority", nullable = false, length = 20)
    private InsightPriority priority;

    /**
     * Whether the user has dismissed this insight.
     *
     * <p>Dismissed insights are hidden from the main view but retained for history. Default: false
     */
    @Column(name = "dismissed", nullable = false)
    @Builder.Default
    private Boolean dismissed = false;

    /** Timestamp when the insight was generated. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Helper method to get user ID directly.
     *
     * @return User ID or null if user not set
     */
    public Long getUserId() {
        return user != null ? user.getId() : null;
    }

    @Override
    public String toString() {
        return "Insight{"
                + "id="
                + id
                + ", userId="
                + getUserId()
                + ", type="
                + type
                + ", title='"
                + title
                + '\''
                + ", priority="
                + priority
                + ", dismissed="
                + dismissed
                + ", createdAt="
                + createdAt
                + '}';
    }
}
