package org.openfinance.mapper;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import org.mapstruct.*;
import org.openfinance.dto.AssetRequest;
import org.openfinance.dto.AssetResponse;
import org.openfinance.entity.Asset;

/**
 * MapStruct mapper for converting between Asset entity and DTOs.
 *
 * <p>This mapper handles bidirectional mapping between:
 *
 * <ul>
 *   <li>{@link AssetRequest} DTO → {@link Asset} entity (for create/update)
 *   <li>{@link Asset} entity → {@link AssetResponse} DTO (for read)
 * </ul>
 *
 * <p><strong>Note:</strong> Encryption and decryption of sensitive fields (name, notes) are handled
 * in the {@link org.openfinance.service.AssetService}, not in this mapper.
 *
 * <p>The {@link #toResponse(Asset)} method includes an {@link AfterMapping} hook to populate
 * calculated fields (totalValue, totalCost, unrealizedGain, gainPercentage, holdingDays) using the
 * Asset entity's calculation methods.
 *
 * <p>Requirement REQ-2.6: Asset Management - DTO conversions for CRUD operations
 *
 * <p>Requirement REQ-2.6.3: Calculate and display portfolio values and gains/losses
 *
 * @see org.openfinance.entity.Asset
 * @see org.openfinance.dto.AssetRequest
 * @see org.openfinance.dto.AssetResponse
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface AssetMapper {

    /**
     * Converts an AssetRequest DTO to an Asset entity.
     *
     * <p>Used when creating a new asset. The userId must be set separately by the service layer
     * after authentication.
     *
     * <p>The following fields are ignored as they are managed by JPA or the service layer:
     *
     * <ul>
     *   <li>id - auto-generated by database
     *   <li>userId - set by service from authenticated user
     *   <li>user, account - JPA managed relationships
     *   <li>lastUpdated - set when prices are updated
     *   <li>createdAt, updatedAt - JPA timestamps
     * </ul>
     *
     * @param request the asset creation request
     * @return a new Asset entity (without id, userId, relationships, timestamps)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "user", ignore = true)
    @Mapping(target = "account", ignore = true)
    @Mapping(target = "lastUpdated", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Asset toEntity(AssetRequest request);

    /**
     * Updates an existing Asset entity from an AssetRequest DTO.
     *
     * <p>This method updates only the fields that are present in the request, preserving the
     * existing values of id, userId, relationships, and timestamps.
     *
     * <p>When updating, lastUpdated timestamp should be set by the service layer if the
     * currentPrice field is modified.
     *
     * @param request the asset update request
     * @param asset the existing asset entity to update
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "user", ignore = true)
    @Mapping(target = "account", ignore = true)
    @Mapping(target = "lastUpdated", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromRequest(AssetRequest request, @MappingTarget Asset asset);

    /**
     * Converts an Asset entity to an AssetResponse DTO.
     *
     * <p>Used when returning asset information to clients. The name and notes fields should already
     * be decrypted by the service layer before calling this method.
     *
     * <p>The {@link #calculateFields(AssetResponse, Asset)} method is automatically invoked after
     * mapping to populate calculated fields (totalValue, totalCost, unrealizedGain, gainPercentage,
     * holdingDays).
     *
     * <p><strong>Note:</strong> The accountName field must be set manually by the service layer
     * after decrypting the account name, as it is encrypted in the database.
     *
     * @param asset the asset entity (with decrypted fields)
     * @return the asset response DTO with all calculated fields populated
     */
    @Mapping(target = "accountName", ignore = true)
    AssetResponse toResponse(Asset asset);

    /**
     * Post-processing hook to populate calculated fields in AssetResponse.
     *
     * <p>This method is automatically invoked by MapStruct after the basic mapping in {@link
     * #toResponse(Asset)} is complete. It uses the Asset entity's calculation methods to populate:
     *
     * <ul>
     *   <li>totalValue = quantity × currentPrice
     *   <li>totalCost = quantity × purchasePrice
     *   <li>unrealizedGain = (currentPrice - purchasePrice) × quantity
     *   <li>gainPercentage = (currentPrice - purchasePrice) ÷ purchasePrice
     *   <li>holdingDays = days between purchase date and current date
     *   <li>depreciatedValue = value after straight-line depreciation (physical assets)
     *   <li>conditionAdjustedValue = depreciated value × condition factor (physical assets)
     *   <li>isPhysical = whether this is a physical asset type
     *   <li>isWarrantyValid = whether warranty is still active
     * </ul>
     *
     * <p>Requirement REQ-2.6.3: Calculate and display portfolio values and gains/losses
     *
     * @param response the partially populated AssetResponse builder
     * @param asset the source Asset entity with calculation methods
     */
    @AfterMapping
    default void calculateFields(
            @MappingTarget AssetResponse.AssetResponseBuilder response, Asset asset) {
        // Populate calculated financial fields using Asset entity methods
        response.totalValue(asset.getTotalValue());
        response.totalCost(asset.getTotalCost());
        response.unrealizedGain(asset.getUnrealizedGain());
        response.gainPercentage(asset.getGainPercentage());

        // Calculate holding days: days between purchase date and now
        if (asset.getPurchaseDate() != null) {
            long days = ChronoUnit.DAYS.between(asset.getPurchaseDate(), LocalDate.now());
            response.holdingDays(days);
        } else {
            response.holdingDays(0L);
        }

        // Populate physical asset calculated fields
        response.depreciatedValue(asset.getDepreciatedValue());
        response.conditionAdjustedValue(asset.getConditionAdjustedValue());
        response.isPhysical(asset.isPhysical());
        response.isWarrantyValid(asset.isWarrantyValid());
    }
}
