package org.openfinance.mapper;

import org.mapstruct.*;
import org.openfinance.dto.RealEstatePropertyRequest;
import org.openfinance.dto.RealEstatePropertyResponse;
import org.openfinance.entity.RealEstateProperty;

/**
 * MapStruct mapper for converting between RealEstateProperty entity and DTOs.
 *
 * <p>This mapper handles bidirectional mapping between:
 *
 * <ul>
 *   <li>{@link RealEstatePropertyRequest} DTO → {@link RealEstateProperty} entity (for
 *       create/update)
 *   <li>{@link RealEstateProperty} entity → {@link RealEstatePropertyResponse} DTO (for read)
 * </ul>
 *
 * <p><strong>Note:</strong> Encryption and decryption of sensitive fields (name, address,
 * purchasePrice, currentValue, rentalIncome, notes, documents) are handled in the {@link
 * org.openfinance.service.RealEstateService}, not in this mapper.
 *
 * <p>The {@link #toResponse(RealEstateProperty)} method includes an {@link AfterMapping} hook to
 * populate calculated fields (appreciation, appreciationPercentage, rentalYield, yearsOwned,
 * equity, equityPercentage, roi) using the RealEstateProperty entity's calculation methods.
 *
 * <p>Requirement REQ-2.16: Real Estate & Physical Assets - DTO conversions for CRUD operations
 *
 * <p>Requirement REQ-2.16.2: Calculate and display property equity, ROI, and appreciation
 *
 * @see org.openfinance.entity.RealEstateProperty
 * @see org.openfinance.dto.RealEstatePropertyRequest
 * @see org.openfinance.dto.RealEstatePropertyResponse
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface RealEstateMapper {

    /**
     * Converts a RealEstatePropertyRequest DTO to a RealEstateProperty entity.
     *
     * <p>Used when creating a new property. The userId must be set separately by the service layer
     * after authentication.
     *
     * <p>The following fields are ignored as they are managed by JPA or the service layer:
     *
     * <ul>
     *   <li>id - auto-generated by database
     *   <li>userId - set by service from authenticated user
     *   <li>user, mortgage - JPA managed relationships
     *   <li>createdAt, updatedAt - JPA timestamps
     * </ul>
     *
     * @param request the property creation request
     * @return a new RealEstateProperty entity (without id, userId, relationships, timestamps)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "user", ignore = true)
    @Mapping(target = "mortgage", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    RealEstateProperty toEntity(RealEstatePropertyRequest request);

    /**
     * Updates an existing RealEstateProperty entity from a RealEstatePropertyRequest DTO.
     *
     * <p>This method updates only the fields that are present in the request, preserving the
     * existing values of id, userId, relationships, and timestamps.
     *
     * @param request the property update request
     * @param property the existing property entity to update
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "userId", ignore = true)
    @Mapping(target = "user", ignore = true)
    @Mapping(target = "mortgage", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateEntityFromRequest(
            RealEstatePropertyRequest request, @MappingTarget RealEstateProperty property);

    /**
     * Converts a RealEstateProperty entity to a RealEstatePropertyResponse DTO.
     *
     * <p>Used when returning property information to clients. The sensitive fields (name, address,
     * purchasePrice, currentValue, rentalIncome, notes, documents) should already be decrypted by
     * the service layer before calling this method.
     *
     * <p>The {@link #calculateFields(RealEstatePropertyResponse.RealEstatePropertyResponseBuilder,
     * RealEstateProperty)} method is automatically invoked after mapping to populate calculated
     * fields (appreciation, appreciationPercentage, rentalYield, yearsOwned, equity,
     * equityPercentage, roi).
     *
     * <p><strong>Note:</strong> The following fields must be set manually by the service layer
     * after mapping because they require decryption or separate database lookups:
     *
     * <ul>
     *   <li>name, address, notes, documents - encrypted fields requiring decryption
     *   <li>purchasePrice, currentValue, rentalIncome - encrypted fields stored as strings, need
     *       decryption then parsing to BigDecimal
     *   <li>mortgageName, mortgageBalance - require separate database lookup and decryption
     *   <li>appreciation, appreciationPercentage, rentalYield - calculated fields based on
     *       decrypted values
     * </ul>
     *
     * @param property the property entity (with encrypted fields still encrypted)
     * @return the property response DTO with basic fields; encrypted/calculated fields must be set
     *     manually
     */
    @Mapping(target = "name", ignore = true)
    @Mapping(target = "address", ignore = true)
    @Mapping(target = "purchasePrice", ignore = true)
    @Mapping(target = "currentValue", ignore = true)
    @Mapping(target = "rentalIncome", ignore = true)
    @Mapping(target = "notes", ignore = true)
    @Mapping(target = "documents", ignore = true)
    @Mapping(target = "mortgageName", ignore = true)
    @Mapping(target = "mortgageBalance", ignore = true)
    @Mapping(target = "appreciation", ignore = true)
    @Mapping(target = "appreciationPercentage", ignore = true)
    @Mapping(target = "rentalYield", ignore = true)
    RealEstatePropertyResponse toResponse(RealEstateProperty property);

    /**
     * Post-processing hook to populate calculated fields in RealEstatePropertyResponse.
     *
     * <p>This method is automatically invoked by MapStruct after the basic mapping in {@link
     * #toResponse(RealEstateProperty)} is complete. It uses the RealEstateProperty entity's
     * calculation methods to populate calculated fields.
     *
     * <p>Requirement REQ-2.16.2: Calculate and display property metrics
     *
     * @param response the partially populated RealEstatePropertyResponse
     * @param property the source RealEstateProperty entity with calculation methods
     */
    @AfterMapping
    default void calculateFields(
            @MappingTarget RealEstatePropertyResponse response, RealEstateProperty property) {
        // Calculated fields will be set by the service layer
        // because they use helper methods that return BigDecimal
    }
}
